### ISSUE TITLE
Migration `sentry 0038_auto_20200213_1904` contains operation(s) that miss `hints={'tables':..}` argument for correctly selecting database connection/alias.

### ISSUE THREAD

**Issue by simseb** [getsentry/onpremise#1010]
### Version Information

Version: 10.1.0.dev0

### Steps to Reproduce

Trying to upgrade to the nightly build... then:

```
▶ Creating additional Kafka topics ...

▶ Ensuring proper PostgreSQL version ...

▶ Setting up / migrating database ...
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Creating sentry_onpremise_memcached_1 ... 
Creating sentry_onpremise_symbolicator_1 ... 
Creating sentry_onpremise_postgres_1     ... 
Creating sentry_onpremise_smtp_1         ... 
Creating sentry_onpremise_snuba-consumer_1 ... 
Creating sentry_onpremise_snuba-subscription-consumer-transactions_1 ... 
Creating sentry_onpremise_snuba-outcomes-consumer_1                  ... 
Creating sentry_onpremise_snuba-replacer_1                           ... 
Creating sentry_onpremise_snuba-subscription-consumer-events_1       ... 
Creating sentry_onpremise_snuba-transactions-consumer_1              ... 
Creating sentry_onpremise_snuba-api_1                                ... 
Creating sentry_onpremise_snuba-sessions-consumer_1                  ... 
Creating sentry_onpremise_memcached_1                                ... done
Creating sentry_onpremise_postgres_1                                 ... done
Creating sentry_onpremise_smtp_1                                     ... done
Creating sentry_onpremise_snuba-outcomes-consumer_1                  ... done
Creating sentry_onpremise_snuba-replacer_1                           ... done
Creating sentry_onpremise_snuba-subscription-consumer-events_1       ... done
Creating sentry_onpremise_snuba-sessions-consumer_1                  ... done
Creating sentry_onpremise_symbolicator_1                             ... done
Creating sentry_onpremise_snuba-transactions-consumer_1              ... done
Creating sentry_onpremise_snuba-consumer_1                           ... done
Creating sentry_onpremise_snuba-subscription-consumer-transactions_1 ... done
Creating sentry_onpremise_snuba-api_1                                ... done
Creating sentry_onpremise_web_run                                    ... 
Creating sentry_onpremise_web_run                                    ... done
10:14:11 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
10:14:11 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
10:14:17 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 196, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 68, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 24, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/sentry/new_migrations/monkey/executor.py", line 74, in apply_migration
    self._check_db_routing(migration)
  File "/usr/local/lib/python3.6/site-packages/sentry/new_migrations/monkey/executor.py", line 56, in _check_db_routing
    f"Migration `{migration.app_label} {migration.name}` contains "
sentry.new_migrations.monkey.executor.MissingDatabaseRoutingInfo: Migration `sentry 0038_auto_20200213_1904` contains operation(s) that miss `hints={'tables':..}` argument for correctly selecting database connection/alias. 
Operations:
<RunSQL '\n                            DROP TABLE "sentry_pagerdutyserviceproject";\n                            ' reverse_sql=''>
1
An error occurred, caught SIGERR on line 12
Cleaning up...
```

Commenting the code (by modifying a container running *getsentry/sentry:nightly*) in ```/usr/local/lib/python3.6/site-packages/sentry/migrations/0038_auto_20200213_1904.py``` leads to the same error in ```0040_remove_incidentsuspectcommittable.py```; commenting that (and i stopped here with commenting) leads to the same problem:

```
[...]
  File "/usr/local/lib/python3.6/site-packages/sentry/new_migrations/monkey/executor.py", line 56, in _check_db_routing
    f"Migration `{migration.app_label} {migration.name}` contains "
sentry.new_migrations.monkey.executor.MissingDatabaseRoutingInfo: Migration `sentry 0047_auto_20200224_2319` contains operation(s) that miss `hints={'tables':..}` argument for correctly selecting database connection/alias. 
Operations:
<RunSQL '\n            ALTER TABLE "sentry_incidentactivity" DROP COLUMN "event_stats_snapshot_id";\n            ' reverse_sql='\n                ALTER TABLE "sentry_incidentactivity" ADD COLUMN "event_stats_snapshot_id" bigint NULL;\n                '>
1
An error occurred, caught SIGERR on line 12
Cleaning up...
```
Any ideas on this? 
Thank You

**Comment by BYK** [comment]
Please see this: https://develop.sentry.dev/self-hosted/#hard-stops

You need to upgrade to `21.6.1` first.
