### ISSUE TITLE
Failed to execute script docker-compose /tmp/tmpwaeg11fj

### ISSUE THREAD

**Issue by anhtung19x9** [getsentry/onpremise#1088]
### Version
Source:  21.8.0 at Master Branch
docker-compose version 1.29.2, build 5becea4c
Docker version 20.10.8, build 3967b7d28e
Ubuntu 20.04.3 LTS

### Steps to Reproduce

./install.sh

### Expected Result

continue install Sentry

### Actual Result

Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> aa82b16af6f0
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 71f371b6166a
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 3c1708be4b6e
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> e994e4251356
Successfully built e994e4251356
Successfully tagged snuba-cleanup-onpremise-local:latest
[24089] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 380, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1948, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwaeg11fj'
An error occurred, caught SIGERR on line 4
Cleaning up..

**Comment by anhtung19x9** [comment]
I found solution and why. Because I install docker use snap in Ubuntu 20.04 so Docker will keep /tmp in /tmp/snap.docker/tmp/. That is the problem when docker-compose check tmp/ of Docker in real /tmp/ in OS. 

Solution: Remove Docker installed by snap by: **snap remove docker** then install again use repository and **apt** command.

**Comment by chadwhitacre** [comment]
Thanks for circling back @anhtung19x9, glad you got it sorted. :)
