### ISSUE TITLE
Upgrading with install.sh

### ISSUE THREAD

**Issue by cmontanaro** [getsentry/onpremise#1091]
### Version

21.8

### Steps to Reproduce

Trying to automate the deployment of sentry onpremise and want to run install.sh when a new node comes up to apply any DB migrations, to do this I have tried the following

1. Bring up instance that has alread had `install.sh` run
1. Run `install.sh`, `sentry upgrade`, or `sentry django migrate`

### Expected Result

Upgrade in place, run db migrations

### Actual Result

Returns `relation "auth_user" already exists` errors

```
unning migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0001_squashed_0200_release_indices...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 77, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "auth_user" already exists


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 77, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: ProgrammingError('relation "auth_user" already exists\n',)
SQL: CREATE TABLE "auth_user" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "id" serial NOT NULL PRIMARY KEY, "username" varchar(128) NOT NULL UNIQUE, "first_name" varchar(200) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "is_superuser" boolean NOT NULL, "is_managed" boolean NOT NULL, "is_sentry_app" boolean NULL, "is_password_expired" boolean NOT NULL, "last_password_change" timestamp with time zone NULL, "flags" bigint NULL, "session_nonce" varchar(12) NULL, "date_joined" timestamp with time zone NOT NULL, "last_active" timestamp with time zone NULL)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 191, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 100, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 56, in _upgrade
    verbosity=verbosity,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/sentry/new_migrations/monkey/executor.py", line 77, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 77, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: ProgrammingError('relation "auth_user" already exists\n',)
SQL: CREATE TABLE "auth_user" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "id" serial NOT NULL PRIMARY KEY, "username" varchar(128) NOT NULL UNIQUE, "first_name" varchar(200) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "is_superuser" boolean NOT NULL, "is_managed" boolean NOT NULL, "is_sentry_app" boolean NULL, "is_password_expired" boolean NOT NULL, "last_password_change" timestamp with time zone NULL, "flags" bigint NULL, "session_nonce" varchar(12) NULL, "date_joined" timestamp with time zone NOT NULL, "last_active" timestamp with time zone NULL)
1
An error occurred, caught SIGERR on line 4
*NOT* cleaning up, to clean your environment run "docker-compose stop".
```

**Comment by chadwhitacre** [comment]
What version are you upgrading from? I _think_ this might indicate that you haven't gone through all of the [hard stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops), but I'm not sure.

**Comment by cmontanaro** [comment]
The original install version was 21.8, I wasn't expecting to get errors just having run the install script a second time through

**Comment by cmontanaro** [comment]
My postgres instance is external from the compose environment

**Comment by BYK** [comment]
>The original install version was 21.8

Was that the tagged version or one of the nightly builds?

> I wasn't expecting to get errors just having run the install script a second time through

You shouldn't under normal circumstances. Either your database in a weird state or you are coming from a nightly that needs to go through one of those hard stops.

**Comment by sauin** [comment]
I got the same error when installing from scratch: clone repo (58874cf) -> install.sh

**Comment by chadwhitacre** [comment]
> I got the same error when installing from scratch: clone repo (58874cf) -> install.sh

I'm not able to repro with these steps. Are you starting from scratch with the database, too, or just the code? The question is what's the state of your database? Maybe the contents of the ... what is it, `django_migrations` table would be interesting?

P.S. My results, showing a clean db hence the prompt to create a user:

```
[...]
13:22:59 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0001_squashed_0200_release_indices... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying nodestore.0001_initial... OK
  Applying nodestore.0002_nodestore_no_dictfield... OK
  Applying sentry.0201_semver_package... OK
  Applying sentry.0202_org_slug_upper_idx... OK
  Applying sentry.0203_groupedmessage_status_index... OK
  Applying sentry.0204_use_project_team_for_team_key_transactions... OK
  Applying sentry.0205_semver_backfill... OK
  Applying sentry.0206_organization_require_email_verification_flag... OK
  Applying sentry.0207_release_adoption... OK
  Applying sentry.0208_add_team_scope... OK
  Applying sentry.0209_avatar_remove_file_fk... OK
  Applying sentry.0210_backfill_project_transaction_thresholds... OK
  Applying sentry.0211_add_artifact_count... OK
  Applying sentry.0212_appconnectbuilds... OK
  Applying sentry.0213_rule_project_status_owner_index... OK
  Applying sentry.0214_activity_project_type_datetime_idx... OK
  Applying sentry.0215_fix_state... OK
  Applying sentry.0216_cdc_setup_replication_index... OK
  Applying sentry.0217_debugfile_remove_project_fk... OK
  Applying sentry.0218_releasefile_remove_fks... OK
  Applying sentry.0219_exporteddatablob_remove_blob_fk... OK
  Applying sentry.0220_add_current_release_version_group_resolution... OK
  Applying sentry.0221_add_appconnect_upload_dates... OK
  Applying sentry.0222_add_datetime_index_to_auditlogentry... OK
  Applying sentry.0223_semver_backfill_2... OK
  Applying sentry.0224_has_sessions_flag... OK
  Applying sentry.0225_latest_appconnect_builds_check... OK
  Applying sentry.0226_add_visits... OK
  Applying sentry.0227_backfill_visits... OK
  Applying sentry.0228_update_auditlog_index_with_entry... OK
  Applying sentry.0229_drop_jiratenant... OK
  Applying sentry.0230_sentry_app_config_jsonfield... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying social_auth.0001_initial... OK
13:23:40 [WARNING] sentry: Cannot initiate onboarding for organization (1) due to missing owners
Created internal Sentry project (slug=internal, id=1)

Would you like to create a user account now? [Y/n]: y
Email: chadwhitacre@sentry.io
Password: 
Repeat for confirmation: 
Added to organization: sentry
User created: chadwhitacre@sentry.io
Creating missing DSNs
Correcting Group.num_comments counter

▶ Migrating file storage ...

▶ Generating Relay credentials ...
Creating ../relay/config.yml...
Creating sentry_onpremise_relay_run ... 
Creating sentry_onpremise_relay_run ... done
Relay credentials written to ../relay/credentials.json

▶ Setting up GeoIP integration ...
Setting up IP address geolocation ...
Installing (empty) IP address geolocation database ... done.
IP address geolocation is not configured for updates.
See https://develop.sentry.dev/self-hosted/geolocation/ for instructions.
Error setting up IP address geolocation.


-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------
```

**Comment by sauin** [comment]
I have given the log of the second attempt of the installation, since the first attempt failed with an error. After deleting all the containers and volumes, the installation was completed successfully. Thanks

**Comment by BYK** [comment]
Thanks a lot for the follow up @sauin, closing the issue then! 🥳

**Comment by chadwhitacre** [comment]
Reopening (after checking with @BYK) since @cmontanaro you are the OP. Any luck on your end?

**Comment by anjia0532** [comment]
https://github.com/getsentry/onpremise/issues/204#issuecomment-456529656
