### ISSUE TITLE
[ERROR] celery.worker.job: Task sentry.tasks.store.save_event[c092365d-609b-454a-a66f-2b7039fb44d8] raised unexpected

### ISSUE THREAD

**Issue by Fabriceli** [getsentry/onpremise#112]
I build sentry and run it with docker, and i can create my project in my sentry website, but i can not get the events. 
SENTRY: 9.0.0
OS: centos7
DOCKER: 1.13.1
DOCKER-COMPOSE: 1.22.0
PYTHON: 2.7.5
PIP: 18.0

I get the logs of the workers:

`11:31:20 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[c092365d-609b-454a-a66f-2b7039fb44d8] raised unexpected: ProgrammingError("ProgrammingError('function sentry_increment_project_counter(integer, integer) does not exist\\nLINE 2:                 select sentry_increment_project_counter(1, 1...\\n                               ^\\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\\n',)\nSQL: \n                select sentry_increment_project_counter(%s, %s)\n            ",) (data={u'hostname': 'celery@0cbe655e887a', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': u'ed0b17bd7f4341f6bcc7063c1c380257', 'cache_key': 'e:ed0b17bd7f4341f6bcc7063c1c380257:1', 'start_time': 1533123080.075781, 'project_id': 1, 'data': None}", u'id': 'c092365d-609b-454a-a66f-2b7039fb44d8'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 332, in save_event
    manager.save(project_id)
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 760, in save
    event=event, hashes=hashes, release=release, **group_kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 1080, in _save_aggregate
    short_id = project.next_short_id()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/project.py", line 133, in next_short_id
    return Counter.increment(self)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/counter.py", line 33, in increment
    return increment_project_counter(project, delta)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/counter.py", line 47, in increment_project_counter
    ''', [project.id, delta]
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 123, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 47, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: ProgrammingError('function sentry_increment_project_counter(integer, integer) does not exist\nLINE 2:                 select sentry_increment_project_counter(1, 1...\n                               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n',)
SQL: 
                select sentry_increment_project_counter(%s, %s)`

Anyone can help me, thanks a lot

**Comment by Fabriceli** [comment]
Well, I fixed this problem, it is not easy.

1. run this command and get in the postgres docker
`docker exec -it onpremise_postgres_1 bash
`
2. get in the postgre database
`psql -h 127.0.0.1 -d postgres -U postgres`

3. run this part program:
`create or replace function sentry_increment_project_counter(
            project bigint, delta int) returns int as $$
        declare
          new_val int;
        begin
          loop
            update sentry_projectcounter set value = value + delta
             where project_id = project
               returning value into new_val;
            if found then
              return new_val;
            end if;
            begin
              insert into sentry_projectcounter(project_id, value)
                   values (project, delta)
                returning value into new_val;
              return new_val;
            exception when unique_violation then
            end;
          end loop;
        end
        $$ language plpgsql;`

Then it works,

Thanks

**Comment by dcramer** [comment]
Your migrations have not been applied correctly as this gets created automatically when migrations complete.

**Comment by Fabriceli** [comment]
I realized that. when i run `docker-compose run --rm web upgrade`， and my computer got stuck
