### ISSUE TITLE
Asana Integration: Internal Server Error

### ISSUE THREAD

**Issue by DanEngelhardt** [getsentry/onpremise#136]
Hi,
I'm trying to link my sentry onpremise installation to our companies asana. 
Whenever I click on "Associate Identity" on the page `/settings/my-org/my-proj/issue-tracking/` under "asana" it gives me an internal server error (500).

`docker logs sentry-onpremise_web_1` gives me the following information:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social_auth/decorators.py", line 27, in wrapper
    raise WrongBackend(backend)
WrongBackend
12:37:59 [ERROR] django.request: Internal Server Error: /account/settings/social/associate/asana/ (status_code=500 request=<WSGIRequest: GET u'/account/settings/social/associate/asana/?next=%2Fsettings%2Fmy-org%2Fmy-project%2Fissue-tracking%2F'>)
```

Version in the footer says "Sentry 9.0.0" if that helps

**Comment by BYK** [comment]
Moving this issue to https://github.com/getsentry/sentry-plugins/ and closing getsentry/sentry#11022 as that's where the Asana integration lives.

There are some light docs on how to set this up (you've probably followed this but just in case): https://docs.sentry.io/workflow/integrations/legacy-integrations/#asana

As the docs mention these are community maintained integrations and we rely on the community to keep these going. From similar issues regarding GitHub, you may need to set up a new API application with Asana (I don't use Asana so don't know much how it works except for standard OAuth). The following docs may also help:

- https://asana.com/developers/documentation/getting-started/auth
- https://python-social-auth-docs.readthedocs.io/en/latest/developer_intro.html
