### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by ilukyanchikov** [getsentry/onpremise#210]
Hey. Faced the following problem. When trying to install Docker image sentry received the following error.

'''19:06:36 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
109.252.51.15 - - [03/Jul/2019:19:06:36 +0000] "GET /auth/login/ HTTP/1.1" 500 5583 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
109.252.51.15 - - [03/Jul/2019:19:06:36 +0000] "GET /_static/1562178818/sentry/images/icons/apple-touch-icon.png HTTP/1.1" 200 6266 "http://localhost:9000/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
'''

Fixed the problem that using `docker-compose run web django shell` have created a User, Organization and OrganizationMember.
Djando migrations seem to be missing the creation of a default organization.

PS I have tried to use createuser there is also not enough default organization

**Comment by BYK** [comment]
Please make sure you have enough RAM available to your Docker images (min 3GB). We highly recommend using the `./install.sh` script in the repo which checks this automatically.

Also, please follow the following best practices when reporting a new issue:

 - Go through existing issues (including closed ones) to see if your problem is already reported.
 - Pick a short and descriptive title for your issue ("BIG PROBLEM" is short but not descriptive)
 - Format your code or log outputs properly using triple backticks (or just use the "code" button on the markup UI)
 - Consider asking about your issue in [the forums](https://forum.sentry.io/c/on-premise) first as this repo is tested to be working at least.
