### ISSUE TITLE
On-Premise docker 9.1.1 - Oops! On fresh install - no default org

### ISSUE THREAD

**Issue by markkimsal** [getsentry/onpremise#228]
I installed sentry from docker with the instructions here:

*  On-Premise docker [docker :latest]
* https://github.com/docker-library/docs/tree/master/sentry

## Description

Oops error when loading the page for the first time.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

## Steps to Reproduce

1. https://github.com/docker-library/docs/tree/master/sentry

The initial `upgrade` command stoped after 429 migrations, I didn't realize there were more.  I tried to "createuser" after these 429 migrations and got this "list index out of range" error.  Now when I create more users I get duplicate key errors (probably because I'm using the same email).

Note that this happens when I simply try to load the system, not when I try to login.

I tried to make another user with different email and the same exception happens.

Sentry is trying to load a default organization when none exists

models/organization.py
```
    @classmethod
    def get_default(cls):
        """
        Return the organization used in single organization mode.
        """
        return cls.objects.filter(
            status=OrganizationStatus.ACTIVE,
        )[0]
```

**Comment by BYK** [comment]
This is a good suggestion, I'll look into the feasibility and UX implications of this. Btw. as far as we know, you need ~3GB RAM available to Docker instances for the initial migration to complete and now we check this beforehand in the `./install.sh` script in this repo (note I have transferred the issue to getsentry/onpremise). 

If that is not accurate I can try increasing the RAM requirement. We are aware that this is not ideal and working towards a better migration setup but it will take some time.

**Comment by BYK** [comment]
We have landed a fix that removes South migrations, dramatically reducing the need for memory during the initial migrations. Although this will only be available from Sentry 10, I'm going to close this issue as we don't plan to do more work on Sentry 9.1.x
