### ISSUE TITLE
sentry.exceptions.InvalidConfiguration connecting to redis:6379

### ISSUE THREAD

**Issue by issaTan** [getsentry/onpremise#240]
I used `sentry` for some months, today I got a OOM with the machine, and when I try to up the container, I got the following error. 
```shell
11:51:55 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
11:51:58 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 73, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 156, in configure
    skip_service_validation=skip_service_validation
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 329, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 352, in setup_services
    service.validate()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 73, in validate
    raise InvalidConfiguration(six.text_type(e))
sentry.exceptions.InvalidConfiguration: Error -3 connecting to redis:6379. Temporary failure in name resolution.
```
But when I log the `redis` server, it was said `The server is now ready to accept connections on port 6379`

Is there anything wrong with my config?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the Sentry on-premise code-related issues.
