### ISSUE TITLE
Uploading symbols not working

### ISSUE THREAD

**Issue by siredmar** [getsentry/onpremise#245]
Hi!

I'm aware of #203 but symbols uploading does not work for me with current master.

I installed this with the install.sh script, added a product and and after successfully login trying to upload a symbol file using

`$ sentry-cli --url http://localhost:9000 upload-dif -t breakpad --org sentry --project crashpad_test main.sym
> Found 1 debug information file
> Prepared debug information file for upload
> Nothing to upload, all files are on the server
`

This is the docker logs output:
```
web_1        | 172.27.0.1 - - [26/Aug/2019:10:34:32 +0000] "GET /api/0/organizations/sentry/chunk-upload/ HTTP/1.1" 200 489 "-" "sentry-cli/1.47.1"
web_1        | 172.27.0.1 - - [26/Aug/2019:10:34:32 +0000] "POST /api/0/projects/sentry/crashpad_test/files/difs/assemble/ HTTP/1.1" 200 322 "-" "sentry-cli/1.47.1"
web_1        | 172.27.0.1 - - [26/Aug/2019:10:34:33 +0000] "POST /api/0/projects/sentry/crashpad_test/reprocessing/ HTTP/1.1" 200 202 "-" "sentry-cli/1.47.1"
worker_1     | celery@377f6e7af89e ready.
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
worker_1     |     R = retval = fun(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1     |     return self.run(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 132, in _inner
worker_1     |     reraise(*exc_info)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 127, in _inner
worker_1     |     return f(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
worker_1     |     result = func(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 27, in assemble_dif
worker_1     |     file_type='project.dif')
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 123, in assemble_file
worker_1     |     temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 463, in assemble_from_file_blob_ids
worker_1     |     for chunk in blob.getfile().chunks():
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 329, in getfile
worker_1     |     return storage.open(self.path)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 33, in open
worker_1     |     return self._open(name, mode)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 159, in _open
worker_1     |     return File(open(self.path(name), mode))
worker_1     | IOError: [Errno 2] No such file or directory: u'/tmp/sentry-files/d7/6df2/241d7741eaac68de78e2249dc8'
worker_1     | 10:34:33 [ERROR] celery.worker.job: Task sentry.tasks.assemble.assemble_dif[6e33de2a-5b6d-423b-a2be-3a799b1f3ef6] raised unexpected: IOError(2, 'No such file or directory') (data={u'hostname': 'celery@377f6e7af89e', u'name': 'sentry.tasks.assemble.assemble_dif', u'args': '[]', u'internal': False, u'kwargs': "{'chunks': ['e6f2e12a8d4d70234013befa803fc3eb60b83afd'], 'checksum': 'e6f2e12a8d4d70234013befa803fc3eb60b83afd', 'project_id': 2L, 'name': 'main.sym'}", u'id': '6e33de2a-5b6d-423b-a2be-3a799b1f3ef6'})
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
postgres_1   | DETAIL:  Key (project_id, hash)=(1, f528764d624db129b32c21fbca0cb8d6) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_eventuser" ("project_id", "hash", "ident", "email", "username", "name", "ip_address", "date_added") VALUES (1, 'f528764d624db129b32c21fbca0cb8d6', NULL, NULL, NULL, NULL, '127.0.0.1', '2019-08-26 10:34:33.364092+00:00') RETURNING "sentry_eventuser"."id"
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
postgres_1   | DETAIL:  Key (project_id, environment_id)=(1, 2) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id", "is_hidden") VALUES (1, 2, NULL) RETURNING "sentry_environmentproject"."id"
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_featureadoption_organization_id_78451b8747a9e638_uniq"
postgres_1   | DETAIL:  Key (organization_id, feature_id)=(1, 0) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_featureadoption" ("organization_id", "feature_id", "date_completed", "complete", "applicable", "data") VALUES (1, 0, '2019-08-26 10:34:33.456617+00:00', true, true, '{}'), (1, 48, '2019-08-26 10:34:33.456772+00:00', true, true, '{}'), (1, 42, '2019-08-26 10:34:33.456823+00:00', true, true, '{}'), (1, 44, '2019-08-26 10:34:33.456884+00:00', true, true, '{}')
```

Does anyone got an idea what is going wrong here?

**Comment by BYK** [comment]
Looks like you have a somewhat broken DB state. Do you think you can have a clean start?

**Comment by BYK** [comment]
Or maybe try running `docker-compose run --rm web upgrade` or `docker-compose run --rm web repair` to force a fix?

**Comment by BYK** [comment]
Closing due to inactivity.
