### ISSUE TITLE
unable to receive chunked part

### ISSUE THREAD

**Issue by attaining** [getsentry/onpremise#248]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/web/api.py", line 498, in post
    data = request.body
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 190, in body
    six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 188, in body
    self._body = self.read()
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 244, in read
    six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 242, in read
    return self._stream.read(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/middleware/proxy.py", line 66, in readinto
    chunk = self.fp.read(Z_CHUNK)
  File "/usr/local/lib/python2.7/site-packages/sentry/middleware/proxy.py", line 30, in readinto
    self._internal_buffer = uwsgi.chunked_read()
UnreadablePostError: unable to receive chunked part
08:12:27 [ERROR] sentry: unable to receive chunked part

**Comment by yuriyprysyazhnyuk** [comment]
I'm getting the same error
![Screenshot from 2019-09-06 17-33-02](https://user-images.githubusercontent.com/25881449/64436175-7ec11680-d0cc-11e9-9b71-bb57bb51f046.png)
![Screenshot from 2019-09-06 17-32-47](https://user-images.githubusercontent.com/25881449/64436176-7ec11680-d0cc-11e9-9f75-4ccdf7e91d54.png)

**Comment by jazerix** [comment]
![image](https://user-images.githubusercontent.com/4068103/66133446-f5333480-e5f6-11e9-83c0-2ebef5d3c4c0.png)
Getting same issue as well :/

**Comment by BYK** [comment]
This should be fixed with https://github.com/getsentry/onpremise/pull/237.
