### ISSUE TITLE
issues  api return 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Go7hic** [getsentry/onpremise#293]
only the issues page have some api return 500, and some api is not
![image](https://user-images.githubusercontent.com/3821390/70198973-6e601c80-174b-11ea-8ac8-de1b26da1036.png)
![image](https://user-images.githubusercontent.com/3821390/70199054-a6fff600-174b-11ea-93ec-eaf170089dd2.png)

but this api not return 500
![image](https://user-images.githubusercontent.com/3821390/70199130-d7e02b00-174b-11ea-8c61-165c1e848c03.png)

**Comment by Go7hic** [comment]
```
docker-compose run --rm web upgrade
Starting onpremise_symbolicator_1 ... done
Starting onpremise_zookeeper_1    ... done
Starting onpremise_postgres_1     ... done
Starting onpremise_clickhouse_1   ... done
Starting onpremise_redis_1        ... done
Starting onpremise_smtp_1         ... done
Starting onpremise_memcached_1    ... done
Starting onpremise_snuba-consumer_1 ... done
Starting onpremise_snuba-consumer_1 ...
Starting onpremise_snuba-api_1      ... done
Starting onpremise_snuba-replacer_1 ... done
02:34:21 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
02:34:25 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'transaction-events.force-disable-internal-project'
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
- Nothing to migrate.
Running migrations for sentry.nodestore:
- Nothing to migrate.
Running migrations for sentry.search:
- Nothing to migrate.
Running migrations for social_auth:
- Nothing to migrate.
Running migrations for sentry.tagstore:
- Nothing to migrate.
Running migrations for sentry_plugins.hipchat_ac:
- Nothing to migrate.
Running migrations for sentry_plugins.jira_ac:
- Nothing to migrate.

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south

Migrated:
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry.tagstore
 - sentry_plugins.hipchat_ac
 - sentry_plugins.jira_ac
Creating missing DSNs
Correcting Group.num_comments counter
```

**Comment by Go7hic** [comment]
```
[INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://xxxx.com/api/0/organizations/wxb/issues/?limit=25&project=2&query=is%3Aunresolved&shortIdLookup=1&statsPeriod=14d' ip_address=u'223.93.139.244' method=u'GET')
web_1                   | Traceback (most recent call last):
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 90, in handle_exception
web_1                   |     response = super(Endpoint, self).handle_exception(exc)
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 190, in dispatch
web_1                   |     response = handler(request, *args, **kwargs)
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_group_index.py", line 158, in get
web_1                   |     'date_from': start,
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_group_index.py", line 40, in _search
web_1                   |     result = search.query(**query_kwargs)
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/search/django/backend.py", line 404, in query
web_1                   |     paginator_options, search_filters, **parameters)
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/search/snuba/backend.py", line 302, in _query
web_1                   |     search_filters=search_filters,
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/search/snuba/backend.py", line 466, in snuba_search
web_1                   |     sample=1,  # Don't use clickhouse sampling, even when in turbo mode.
web_1                   |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 495, in raw_query
web_1                   |     )(error['message'])
web_1                   | QueryExecutionError: Code: 62.
web_1                   | DB::Exception: Syntax error: failed at position 121: () AS last_seen) FROM sentry_local SAMPLE 1 PREWHERE issue IN (3, 6, 4, 7, 8) WHERE project_id IN (2) AND timestamp >= toDateTime('2019-11-21T03:04:27') AND tim. Expected one of: NOT, AS, LIKE, AND, OR, IN, BETWEEN, alias, token, IS, NOT LIKE, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, QuestionMark. Stack trace:
web_1                   |
web_1                   | 0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x6f8abf6]
web_1                   | 1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x372c822]
web_1                   | 2. /usr/bin/clickhouse-server(DB::parseQuery(DB::IParser&, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)+0xac) [0x6c1e36c]
web_1                   | 3. /usr/bin/clickhouse-server() [0x6574305]
web_1                   | 4. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0x81) [0x6576141]
web_1                   | 5. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x752) [0x3739f82]
web_1                   | 6. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x373a5cb]
web_1                   | 7. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x708e5af]
web_1                   | 8. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x708ece9]
web_1                   | 9. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7141f81]
web_1                   | 10. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x713e148]
web_1                   | 11. /usr/bin/clickhouse-server() [0xae06d1f]
web_1                   | 12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fca2cfa66db]
web_1                   | 13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fca2c52588f]
```
