### ISSUE TITLE
Sentry not send email

### ISSUE THREAD

**Issue by luffyZh** [getsentry/onpremise#337]
I follow the issue #71 ,but the solution not works.

- config.yml
```
mail.backend: 'django_smtp_ssl.SSLEmailBackend' // default don't send email either.
mail.host: 'smtp.163.com'
mail.port: 465
mail.username: 'luffyzh@163.com'
mail.password: 'xxxxxx'
mail.use-tls: true
# The email address to send on behalf of
mail.from: 'luffyzh@163.com'
```
![图片](https://user-images.githubusercontent.com/17840558/72127941-29fc1800-33ac-11ea-8165-08e82ed4e0cd.png)
![图片](https://user-images.githubusercontent.com/17840558/72127952-32545300-33ac-11ea-8691-ef554b1917dd.png)
![图片](https://user-images.githubusercontent.com/17840558/72127979-5021b800-33ac-11ea-8f32-2b0eb0b6f386.png)

- The senter_worker logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 77, in send_email
    send_messages([message])
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 413, in send_messages
    sent = connection.send_messages(messages)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django_smtp_ssl.py", line 12, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/local/lib/python2.7/smtplib.py", line 802, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 318, in connect
    (code, msg) = self.getreply()
  File "/usr/local/lib/python2.7/smtplib.py", line 366, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: ('The read operation timed out',)
05:13:22 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[08103d4f-8eda-4dc4-95f2-6d463cfdbbb1] raised unexpected: SMTPServerDisconnected("Connection unexpectedly closed: ('The read operation timed out',)",) (data={u'hostname': 'celery@e2c758c5b329', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f9ec49359d0>}", u'id': '08103d4f-8eda-4dc4-95f2-6d463cfdbbb1'})
```

**Comment by BYK** [comment]
It seems like a network error when trying to connect your mail server. The stacktrace suggests it may be during the DNS name resolution but not sure.

**Comment by BYK** [comment]
This may also help you: https://stackoverflow.com/a/47328415/90297

**Comment by luffyZh** [comment]
@BYK Thanks, i will try it~

**Comment by BYK** [comment]
Also from https://github.com/getsentry/sentry/issues/4252 you may want to turn TLS off in your settings.

**Comment by aadlani** [comment]
I have the same issue here. I'm sending with SendGrid, and I tried TLS, SSL and unencrypted, and it all fail with the DNS resolution issue that you mentionned earlier. `[Errno -3] Temporary failure in name resolution`. I'm currently trying to debbug the situation.

**Comment by aadlani** [comment]
Ok, after checking, this is clearly a DNS issue related to the docker configuration and not to the sentry on-premise. For me, it was due to my setup to avoid the conflict between IPTables/UFW.

**Comment by BYK** [comment]
Thanks for sharing @aadlani! Closing the issue for now until someone can prove this is on Sentry.
