### ISSUE TITLE
SnubaError leads to HTTP error 500 because it tries to connect to localhost

### ISSUE THREAD

**Issue by tristanleboss** [getsentry/onpremise#344]
Hello,

I have the exact same problem as this guy: https://forum.sentry.io/t/snubaerror-and-500-internal-error/8182/2

Because of this, I am opening this issue.

I followed the basic setup (git clone, ./install, docker-compose up -d): everything seemed to be fine.
The UI is working but a lot of ajax requests returns errors 500.

The error is:

```
00:18:24 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'https://sentry.crealya.fr/api/0/organizations/sentry/issues/?limit=25&query=is%3Aunresolved&shortIdLookup=1&statsPeriod=14d' method=u'GET' ip_address=u'77.159.160.34')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 89, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 196, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_group_index.py", line 176, in get
    {"count_hits": True, "date_to": end, "date_from": start},
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_group_index.py", line 45, in _search
    result = search.query(**query_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/search/snuba/backend.py", line 181, in query
    date_to=date_to,
  File "/usr/local/lib/python2.7/site-packages/sentry/search/snuba/executors.py", line 405, in query
    search_filters=search_filters,
  File "/usr/local/lib/python2.7/site-packages/sentry/search/snuba/executors.py", line 193, in snuba_search
    sample=1,  # Don't use clickhouse sampling, even when in turbo mode.
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 1003, in dataset_query
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 714, in raw_query
    return bulk_raw_query([snuba_params], referrer=referrer)[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 746, in bulk_raw_query
    query_results = [snuba_query(query_param_list[0])]
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 739, in snuba_query
    raise SnubaError(err)
SnubaError: HTTPConnectionPool(host='localhost', port=1218): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4fe8663e50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

The line 22 of the `docker-compose.yml` is:

```
 environment:
    SNUBA: 'http://snuba-api:1218'
```

So, I don't understand why it does try to connect to localhost?

I was thinking this environment variable may not be used and so, it defaults to "http://localhost:1218".

**Comment by BYK** [comment]
Nope, it is here and is being used: https://github.com/getsentry/sentry/blame/master/src/sentry/conf/server.py

Please check your config files.

**Comment by BYK** [comment]
Closing due to lack of response.
