### ISSUE TITLE
clean / first install fails with: /etc/sentry/docker-entrypoint.sh: line 20: [: missing `]' /etc/sentry/docker-entrypoint.sh: line 20: 999: command not found

### ISSUE THREAD

**Issue by ProxiBlue** [getsentry/onpremise#382]
Looks like something in one of the supplied docker images has been broken.

Simply did a git clone of this repo, and ran install.sh

```
Setting up database...
Starting sentry_onpremise_zookeeper_1_cd29147b3192 ... 
Starting sentry_onpremise_zookeeper_1_cd29147b3192 ... done
Creating sentry_onpremise_postgres_1_d9a0c866b4b7  ... 
Creating sentry_onpremise_smtp_1_ec13c9db0777      ... 
Creating sentry_onpremise_symbolicator_1_1c612b147b96 ... 
Creating sentry_onpremise_memcached_1_6533397dfab0    ... 
Starting sentry_onpremise_redis_1_692033d3d589        ... 
Starting sentry_onpremise_clickhouse_1_8cecdcca484c   ... 
Starting sentry_onpremise_redis_1_692033d3d589        ... done
Starting sentry_onpremise_clickhouse_1_8cecdcca484c   ... done
Starting sentry_onpremise_kafka_1_19207b8fdfce        ... 
Starting sentry_onpremise_kafka_1_19207b8fdfce        ... done
Creating sentry_onpremise_snuba-consumer_1_ed977712e326 ... 
Creating sentry_onpremise_snuba-replacer_1_3f837d2e38c3 ... 
Creating sentry_onpremise_snuba-api_1_52674e7d9953      ... 
Creating sentry_onpremise_smtp_1_ec13c9db0777           ... done
Creating sentry_onpremise_memcached_1_6533397dfab0      ... done
Creating sentry_onpremise_postgres_1_d9a0c866b4b7       ... done
Creating sentry_onpremise_snuba-replacer_1_3f837d2e38c3 ... done
Creating sentry_onpremise_snuba-consumer_1_ed977712e326 ... done
Creating sentry_onpremise_snuba-api_1_52674e7d9953      ... done
Creating sentry_onpremise_symbolicator_1_1c612b147b96   ... done
/etc/sentry/docker-entrypoint.sh: line 20: [: missing `]'
/etc/sentry/docker-entrypoint.sh: line 20: 999: command not found
07:41:25 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
07:41:49 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 66, in worker
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 104, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redissnuba.py", line 85, in method
    return getattr(self.backends[backend], key)(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 203, in incr
    self.incr_multi([(model, key)], timestamp, count, environment_id)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 262, in incr_multi
    client.hincrby(hash_key, hash_field, count)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1865, in hincrby
    return self.execute_command('HINCRBY', name, key, amount)
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 333, in execute_command
    buf = self._get_command_buffer(host_id, args[0])
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 351, in _get_command_buffer
    buf = CommandBuffer(host_id, connect, self.auto_batch)
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 90, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 109, in connect
    self.connection.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to redis:6379. Connection refused.
```

**Comment by ProxiBlue** [comment]
The main issue is here:

```
/etc/sentry/docker-entrypoint.sh: line 20: [: missing `]'
/etc/sentry/docker-entrypoint.sh: line 20: 999: command not found
```

**Comment by repomaa** [comment]
Can confirm this

**Comment by BYK** [comment]
This should be fixed now, sorry for the inconvenience.

**Comment by ProxiBlue** [comment]
Hello, confirmed fixed. Thank you very much.
