### ISSUE TITLE
Cannot upgrade from 9.1.2 to 10

### ISSUE THREAD

**Issue by chapa** [getsentry/onpremise#435]
Hello,

I'm facing a very confusing problem, yet different from all other issues related to 9.1.2 -> 10 migrations that I could see.

I came from a 8.22 version, upgraded to 9.0 then to 9.1.2. Until there no problem, but I cannot migrate to v10 because I have the following error message :
```
Exception: Please upgrade to Sentry 9.1.2 before upgrading to any later versions.
```

Here is the output when I run `docker-compose run --rm web upgrade` at tag 9.1.2 :
```
Starting sentry_memcached_1 ... done
Starting sentry_postgres_1  ... done
Starting sentry_smtp_1      ... done
17:54:59 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
17:55:07 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for sentry:
- Nothing to migrate.
Running migrations for sentry.nodestore:
- Nothing to migrate.
Running migrations for sentry.search:
- Nothing to migrate.
Running migrations for social_auth:
- Nothing to migrate.
Running migrations for sentry.tagstore:
- Nothing to migrate.
Running migrations for sentry_plugins.hipchat_ac:
- Nothing to migrate.
Running migrations for sentry_plugins.jira_ac:
- Nothing to migrate.

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > sudo
 > south

Migrated:
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
 - sentry.tagstore
 - sentry_plugins.hipchat_ac
 - sentry_plugins.jira_ac
Creating missing DSNs
Correcting Group.num_comments counter
```
(this is not the first time I've run this command, but we can see there is nothing more to migrate)

Then I checkout master and run `./install.sh` (after updating config files because they are not at the same place, etc...), and :
```
[... a lot of things ...]

Setting up database...
Starting sentry_zookeeper_1 ... 
Starting sentry_zookeeper_1 ... done
Starting sentry_clickhouse_1 ... 
Creating sentry_postgres_1   ... 
Starting sentry_clickhouse_1 ... done
Creating sentry_memcached_1  ... 
Creating sentry_symbolicator_1 ... 
Starting sentry_redis_1      ... 
Starting sentry_redis_1        ... done
Creating sentry_smtp_1       ... 
Starting sentry_kafka_1        ... 
Starting sentry_kafka_1        ... done
Creating sentry_snuba-consumer_1 ... 
Creating sentry_snuba-api_1      ... 
Creating sentry_snuba-replacer_1 ... 
Creating sentry_snuba-outcomes-consumer_1 ... 
Creating sentry_symbolicator_1            ... done
Creating sentry_snuba-api_1               ... done
Creating sentry_snuba-replacer_1          ... done
Creating sentry_postgres_1                ... done
Creating sentry_memcached_1               ... done
Creating sentry_smtp_1                    ... done
Creating sentry_snuba-outcomes-consumer_1 ... done
Creating sentry_snuba-consumer_1          ... done
18:00:10 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
18:00:22 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 168, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 114, in _migrate_from_south
    raise Exception(south_migration_required_error)
Exception: Please upgrade to Sentry 9.1.2 before upgrading to any later versions.
Cleaning up...
```

A dig a little bit more, but I really don't understand what I'm seeing.

First I entered the container with `docker-compose run web bash`
I found the place in the code where the exception is thrown, so I try to add a `print` to see what migration is missing :
```python
def _has_applied_south_migration(connection, app_name, migration):
    if migration is None:
        return True
    cursor = connection.cursor()
    try:
        print("Migration " + app_name + " - " + migration) // <-- HERE
        cursor.execute(
            "SELECT 1 FROM south_migrationhistory WHERE app_name = %s AND migration = %s LIMIT 1",
            [app_name, migration],
        )
        return bool(cursor.fetchall())
    finally:
        cursor.close()
```

Output when executing `sentry upgrade` (from the container where I edit the code) :
```
18:33:33 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
18:33:42 [INFO] sentry.plugins.github: apps-not-configured
Migration sentry - 0472_auto__add_field_sentryapp_author
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 169, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 122, in _upgrade
    _migrate_from_south(verbosity)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 115, in _migrate_from_south
    raise Exception(south_migration_required_error)
Exception: Please upgrade to Sentry 9.1.2 before upgrading to any later versions.
```

So we can see at the beginning, `app_name == 'sentry'` and `migration == '0472_auto__add_field_sentryapp_author'`.

I wanted to execute the SQL request myself, so I installed `psql` inside the container, and `psql -h postgres --user sentry`, to be sure I'm accessing the right database :sweat_smile:

And here's the joke :
```
sentry=# SELECT 1 FROM south_migrationhistory WHERE app_name = 'sentry' AND migration = '0472_auto__add_field_sentryapp_author';
 ?column? 
----------
        1
(1 row)
```

How can this possibly happen ?
Thanks to whoever can help me with this migration...

Please ask me if you want more details, I'll come back in 9.1.2 for now to bring my sentry back online until we find a solution.

PS: I cannot just remove the database, since I have data I don't want to lose.

**Comment by BYK** [comment]
Hi @chapa, sorry this went unanswered. Were you able to fix your issue?

**Comment by chapa** [comment]
Hi, no I didn't know what to look for when I wrote the issue so I stayed in version 9.1.2, and I didn't give it another try

**Comment by BYK** [comment]
@chapa would you mind trying this again from latest master and sharing your full install logs if it still fails?

Please make a backup of your existing data (mostly Postgres) just in case.

**Comment by chapa** [comment]
Yeah I'll try that when I have time

**Comment by TengfeiQi** [comment]
@BYK I'm facing same very confusing problem too. here is my log:
when i exec `docker-compose run --rm web upgrade`
```
Creating network "sentry9_default" with the default driver
Creating sentry9_smtp_1      ... done
Creating sentry9_postgres_1  ... done
Creating sentry9_memcached_1 ... done
Creating sentry9_redis_1     ... done
06:29:32 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
06:29:35 [INFO] sentry.plugins.github: apps-not-configured
Syncing...
Creating tables ...
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 119, in handle_noargs
    self.sync_apps(apps_needing_sync, app_name_to_app_map, options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 174, in sync_apps
    syncdb.Command().execute(**options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 112, in handle_noargs
    emit_post_sync_signal(created_models, verbosity, interactive, db)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/sql.py", line 216, in emit_post_sync_signal
    interactive=interactive, db=db)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 82, in create_permissions
    ctype = ContentType.objects.db_manager(db).get_for_model(klass)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 47, in get_for_model
    defaults = {'name': smart_text(opts.verbose_name_raw)},
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 376, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 446, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 74, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.ProgrammingError: ProgrammingError('column django_content_type.name does not exist\nLINE 1: SELECT "django_content_type"."id", "django_content_type"."na...\n                                           ^\n',)
SQL: SELECT "django_content_type"."id", "django_content_type"."name", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = %s  AND "django_content_type"."app_label" = %s )
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-1, stopped daemon 140083193116416)>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/local/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

**Comment by BYK** [comment]
@TengfeiQi I don't expect anyone to manually run the upgrade command as the install script takes care of it automatically. Your issue seems like a case of this, and different from what @chapa reported: https://stackoverflow.com/a/37860670/90297

@chapa - are you still stuck with this or were you able to upgrade?

**Comment by chapa** [comment]
I'm sorry I really don't have time to get into it right now, and since the upgrade is far from being a priority I don't know when I'll be able to give a try.

I'm ok if you want to close the issue for now, I'll come and reopen it if I still have the problem the day I try :wink:
