### ISSUE TITLE
./install.sh Failed to execute script docker-compose

### ISSUE THREAD

**Issue by manfwh** [getsentry/onpremise#436]
```Checking minimum requirements...
Removing network onpremise_default
Network onpremise_default not found.
Removing network sentry_onpremise_default
Network sentry_onpremise_default not found.

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.

Building and tagging Docker images...

Pulling smtp                    ... 

Pulling memcached               ... 

Pulling redis                   ... 

Pulling postgres                ... 

Pulling zookeeper               ... 

Pulling kafka                   ... 

Pulling clickhouse              ... 

Pulling snuba-api               ... 

Pulling snuba-consumer          ... 

Pulling snuba-outcomes-consumer ... 

Pulling snuba-replacer          ... 

Pulling snuba-cleanup           ... 

Pulling symbolicator            ... 

Pulling symbolicator-cleanup    ... 

Pulling web                     ... 

Pulling cron                    ... 

Pulling worker                  ... 

Pulling post-process-forwarder  ... 

Pulling sentry-cleanup          ... 

[22032] Failed to execute script docker-compose

ERROR: for snuba-outcomes-consumer  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for worker  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for snuba-replacer  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for kafka  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for sentry-cleanup  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for clickhouse  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for symbolicator  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for memcached  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for web  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for redis  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for symbolicator-cleanup  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for post-process-forwarder  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for snuba-cleanup  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for postgres  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for zookeeper  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for smtp  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for snuba-consumer  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for cron  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')

ERROR: for snuba-api  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages\docker\credentials\store.py", line 35, in get
  File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 747, in pull
  File "compose\project.py", line 630, in pull
  File "compose\project.py", line 678, in parallel_pull
  File "compose\parallel.py", line 112, in parallel_execute
  File "compose\parallel.py", line 210, in producer
  File "compose\project.py", line 660, in pull_service
  File "compose\service.py", line 1215, in _do_pull
  File "site-packages\docker\api\image.py", line 396, in pull
  File "site-packages\docker\auth.py", line 48, in get_config_header
  File "site-packages\docker\auth.py", line 324, in resolve_authconfig
  File "site-packages\docker\auth.py", line 235, in resolve_authconfig
  File "site-packages\docker\auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')
Cleaning up...
```

**Comment by BYK** [comment]
It already tells you what the issue is:
```
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``".')
```

This is not something the install script can fix.
