### ISSUE TITLE
sentry-worker can't send email

### ISSUE THREAD

**Issue by ST9527** [getsentry/onpremise#45]
It works when I first stared the container.But recently it failed.
I run `docker logs sentry-worker-03` and I see this: 

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 72, in send_email
    send_messages([message])
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 405, in send_messages
    sent = connection.send_messages(messages)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```
Looks like the container can not connect to the smtp server.I tried it on my host and it works!
So I connected to the container with : `docker exec -it sentry-worker-03 /bin/bash` .
And I run : 
``` bash
root@79f41d34850b:/usr/src/sentry# python
Python 2.7.13 (default, Jun 21 2017, 18:17:05)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import smtplib
>>> s = smtplib.SMTP("smtp.exmail.qq.com:587")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
>>>
```
So it looks like the container can not connect to the Internet.
How can I make it right? Sorry for my poor English.

**Comment by mattrobenolt** [comment]
I don’t know. But this is networking issue for you with Docker. Nothing to do with Sentry.

**Comment by loganx510** [comment]
I have same problem with docker.
```
# cat ./docker-compose.yml

environment:
      SENTRY_SECRET_KEY: '*****'
      SENTRY_EMAIL_HOST: 10.138.0.20
      SENTRY_EMAIL_PORT: 25
      SENTRY_SERVER_EMAIL: ***@***.com

docker exec -it 731800025f4d bash

root@731800025f4d:/usr/src/sentry# echo $SENTRY_EMAIL_HOST
10.138.0.20
root@731800025f4d:/usr/src/sentry# echo $SENTRY_EMAIL_PORT
25
root@731800025f4d:/usr/src/sentry# telnet 10.138.0.20 smtp
Trying 10.138.0.20...
Connected to 10.138.0.20.
Escape character is '^]'.
220 error.c.second-jet-156123.internal ESMTP Postfix (Ubuntu)
mail from: support@****.com
250 2.1.0 Ok
rcpt to: user@***.com
250 2.1.5 Ok
data
354 End data with <CR><LF>.<CR><LF>
Hi

.
250 2.0.0 Ok: queued as DC3C8BBCCB
```

However when I try to send an email I have:

```
docker logs 731800025f4d --follow

celery@731800025f4d ready.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 72, in send_email
    send_messages([message])
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 405, in send_messages
    sent = connection.send_messages(messages)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
23:05:59 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[0c90ae96-511e-4bb1-a980-9d6a6fca7d15] raised unexpected: timeout('timed out',) (data={u'hostname': 'celery@731800025f4d', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f041dc04750>}", u'id': '0c90ae96-511e-4bb1-a980-9d6a6fca7d15'})    
```

@mattrobenolt is it enough to just set ENV vars ? or I should do enything else ?

Thanks

**Comment by xorander00** [comment]
DNS issue of some sort.  Host is resolving fine, but the container is not.  Looking into it now.

**Comment by xorander00** [comment]
Turned out to be a networking issue in my environment.  I'm running the host server as a Kubernetes node as well, which changes the default docker network.  I had to unlink the services in docker-compose, since I have my own dedicated boxes for those, and then explicitly set the network to host.
