### ISSUE TITLE
sentry can't open in the web

### ISSUE THREAD

**Issue by zhankenson** [getsentry/onpremise#455]
I run docker-compose up -d, all containers seems no problems.I open 127.0.0.1:8888,but it  can't open in the web.

**docker ps:**
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                            NAMES
d67c46bd7709        nginx:1.16                             "nginx -g 'daemon of…"   22 minutes ago      Up 22 minutes       80/tcp, 0.0.0.0:8888->9000/tcp   sentry_onpremise_nginx_1
97b85cf00d07        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   22 minutes ago      Up 22 minutes       9000/tcp                         sentry_onpremise_ingest-consumer_1
cdc435cb9708        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   22 minutes ago      Up 22 minutes       9000/tcp                         sentry_onpremise_worker_1
6fde584b391a        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   22 minutes ago      Up 22 minutes       9000/tcp                         sentry_onpremise_web_1
1073f3ca6447        sentry-cleanup-onpremise-local         "/entrypoint.sh '0 0…"   22 minutes ago      Up 22 minutes       9000/tcp                         sentry_onpremise_sentry-cleanup_1
ed9efa58cc12        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   22 minutes ago      Up 22 minutes       9000/tcp                         sentry_onpremise_post-process-forwarder_1
d66d151760b2        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   22 minutes ago      Up 22 minutes       9000/tcp                         sentry_onpremise_cron_1
73bff6b62a13        snuba-cleanup-onpremise-local          "/entrypoint.sh '*/5…"   22 minutes ago      Up 22 minutes       1218/tcp                         sentry_onpremise_snuba-cleanup_1
ad8d539d1419        getsentry/relay:latest                 "/bin/bash /docker-e…"   22 minutes ago      Up 22 minutes       3000/tcp                         sentry_onpremise_relay_1
335424fa4e42        symbolicator-cleanup-onpremise-local   "/entrypoint.sh '55 …"   22 minutes ago      Up 22 minutes       3021/tcp                         sentry_onpremise_symbolicator-cleanup_1
00301f3fdc07        getsentry/snuba:latest                 "./docker_entrypoint…"   23 minutes ago      Up 22 minutes       1218/tcp                         sentry_onpremise_snuba-outcomes-consumer_1
43b07fe03a0d        getsentry/snuba:latest                 "./docker_entrypoint…"   23 minutes ago      Up 22 minutes       1218/tcp                         sentry_onpremise_snuba-consumer_1
a37f836901a3        getsentry/snuba:latest                 "./docker_entrypoint…"   23 minutes ago      Up 22 minutes       1218/tcp                         sentry_onpremise_snuba-api_1
ff31de271db4        getsentry/snuba:latest                 "./docker_entrypoint…"   23 minutes ago      Up 22 minutes       1218/tcp                         sentry_onpremise_snuba-replacer_1
945067ba7df0        tianon/exim4                           "docker-entrypoint.s…"   23 minutes ago      Up 22 minutes       25/tcp                           sentry_onpremise_smtp_1
00bd02d53ae7        postgres:9.6                           "docker-entrypoint.s…"   23 minutes ago      Up 22 minutes       5432/tcp                         sentry_onpremise_postgres_1
b14f8a4e2d94        memcached:1.5-alpine                   "docker-entrypoint.s…"   23 minutes ago      Up 22 minutes       11211/tcp                        sentry_onpremise_memcached_1
71b32a5a734a        getsentry/symbolicator:latest          "/bin/bash /docker-e…"   23 minutes ago      Up 22 minutes       3021/tcp                         sentry_onpremise_symbolicator_1
3a0e0275fd46        confluentinc/cp-kafka:5.1.2            "/etc/confluent/dock…"   23 minutes ago      Up 22 minutes       9092/tcp                         sentry_onpremise_kafka_1
dc322198366f        confluentinc/cp-zookeeper:5.1.2        "/etc/confluent/dock…"   23 minutes ago      Up 22 minutes       2181/tcp, 2888/tcp, 3888/tcp     sentry_onpremise_zookeeper_1
9ae5c26a7ccd        yandex/clickhouse-server:19.11         "/entrypoint.sh"         23 minutes ago      Up 22 minutes       8123/tcp, 9000/tcp, 9009/tcp     sentry_onpremise_clickhouse_1
0413ada61f29        redis:5.0-alpine                       "docker-entrypoint.s…"   23 minutes ago      Up 22 minutes       6379/tcp                         sentry_onpremise_redis_1

**I print getsentry/relay container logs,It gets:**
2020-04-29T05:51:11Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#172.29.0.10:9092 failed: Connection refused (after 25ms in state CONNECT)
2020-04-29T05:51:11Z [rdkafka::client] ERROR: librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 1/1 brokers are down
2020-04-29T05:51:11Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#172.29.0.10:9092 failed: Connection refused (after 2ms in state CONNECT)
2020-04-29T05:51:11Z [rdkafka::client] ERROR: librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 1/1 brokers are down
2020-04-29T05:51:12Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-04-29T05:51:13Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Timeout while waiting for response
2020-04-29T05:51:14Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
2020-04-29T05:51:15Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
2020-04-29T05:51:18Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
2020-04-29T05:51:21Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Connection refused (os error 111)
  caused by: Connection refused (os error 111)
  caused by: Connection refused (os error 111)

**I print kafka logs,it gets:**
[2020-04-29 06:36:33,415] WARN [RequestSendThread controllerId=1001] Controller 1001's connection to broker kafka:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.lang.IllegalStateException: No entry found for connection 1001
	at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:339)
	at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:143)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:279)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:233)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)

How should I do?

**Comment by zhankenson** [comment]
I delete all images and old git files,clone new files and install,it runs,so amazing!
