### ISSUE TITLE
GitLab integration setup yields 504 Gateway Time-out after redirect from GitLab

### ISSUE THREAD

**Issue by caugner** [getsentry/onpremise#505]
I tried to setup the GitLab integration, but after `Authorize`ing the application in GitLab I get redirected to our Sentry instance at `https://sentry.***.net/extensions/gitlab/setup/?code=***&state=***` which responds with a `504 Gateway Time-out`.

`docker-compose logs -f` showed the following:

```sh
web_1                      | 13:33:01 [INFO] sentry.integration.gitlab: gitlab.setup.installation-config-view.success (base_url=u'https://gitlab.***.net' verify_ssl=True client_id=u'***')
nginx_1                    | 172.18.0.1 - - [20/May/2020:13:33:01 +0000] "POST /extensions/gitlab/setup/?completed_installation_guide HTTP/1.0" 302 0 "https://sentry.***.net/extensions/gitlab/setup/?completed_installation_guide" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
web_1                      | 172.18.0.23 - - [20/May/2020:13:33:01 +0000] "POST /extensions/gitlab/setup/?completed_installation_guide HTTP/1.0" 302 1056 "https://sentry.***.net/extensions/gitlab/setup/?completed_installation_guide" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
nginx_1                    | 172.18.0.1 - - [20/May/2020:13:33:20 +0000] "GET /extensions/gitlab/setup/?code=***&state=*** HTTP/1.0" 499 0 "https://gitlab.***.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
web_1                      | 13:33:20 [WARNING] django.request: Not Found: /favicon.ico (status_code=404 request=<WSGIRequest: GET u'/favicon.ico'>)
nginx_1                    | 172.18.0.1 - - [20/May/2020:13:33:20 +0000] "GET /favicon.ico HTTP/1.0" 404 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
web_1                      | 172.18.0.23 - - [20/May/2020:13:33:20 +0000] "GET /favicon.ico HTTP/1.0" 404 792 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
web_1                      | Traceback (most recent call last):
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1                      |     response = get_response(request)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1                      |     response = self._get_response(request)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1                      |     response = self.process_exception_by_middleware(e, request)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1                      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
web_1                      |     return self.dispatch(request, *args, **kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1                      |     return view_func(*args, **kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 227, in dispatch
web_1                      |     return self.handle(request, *args, **kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/pipeline_advancer.py", line 53, in handle
web_1                      |     return pipeline.current_step()
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 224, in current_step
web_1                      |     return step.dispatch(request=self.request, pipeline=self)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 97, in dispatch
web_1                      |     return nested_pipeline.current_step()
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 224, in current_step
web_1                      |     return step.dispatch(request=self.request, pipeline=self)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1                      |     return view_func(*args, **kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 236, in dispatch
web_1                      |     return pipeline.next_step()
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 235, in next_step
web_1                      |     return self.current_step()
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/pipeline/__init__.py", line 224, in current_step
web_1                      |     return step.dispatch(request=self.request, pipeline=self)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 321, in dispatch
web_1                      |     data = self.exchange_token(request, pipeline, code)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/identity/oauth2.py", line 278, in exchange_token
web_1                      |     req = safe_urlopen(self.access_token_url, data=data, verify_ssl=verify_ssl)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/http.py", line 117, in safe_urlopen
web_1                      |     **kwargs
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry/net/http.py", line 150, in request
web_1                      |     response = _Session.request(self, *args, **kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
web_1                      |     resp = self.send(prep, **send_kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
web_1                      |     r = adapter.send(request, **kwargs)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
web_1                      |     raise ConnectionError(e, request=request)
web_1                      | ConnectionError: SafeHTTPSConnectionPool(host='gitlab.***.net', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<sentry.net.http.SafeHTTPSConnection object at 0x7fc8c423e890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
web_1                      | 13:33:25 [ERROR] django.request: Internal Server Error: /extensions/gitlab/setup/ (status_code=500 request=<WSGIRequest: GET u'/extensions/gitlab/setup/?code=***&state=***'>)
web_1                      | 172.18.0.23 - - [20/May/2020:13:33:15 +0000] "GET /extensions/gitlab/setup/?code=***&state=*** HTTP/1.0" 500 6828 "https://gitlab.***.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
web_1                      | Traceback (most recent call last):
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/transport.py", line 296, in send_event_wrapper
web_1                      |     self._send_event(event)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/transport.py", line 217, in _send_event
web_1                      |     headers={"Content-Type": "application/json", "Content-Encoding": "gzip"},
web_1                      |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/transport.py", line 164, in _send_request
web_1                      |     "POST", str(self._auth.store_api_url), body=body, headers=headers
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 72, in request
web_1                      |     **urlopen_kw)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
web_1                      |     return self.urlopen(method, url, **extra_kw)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
web_1                      |     response = conn.urlopen(method, u.request_uri, **kw)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
web_1                      |     **response_kw)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
web_1                      |     **response_kw)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
web_1                      |     **response_kw)
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
web_1                      |     _stacktrace=sys.exc_info()[2])
web_1                      |   File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 399, in increment
web_1                      |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
web_1                      | MaxRetryError: HTTPSConnectionPool(host='sentry.***.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc8c423ea50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
web_1                      | 13:33:27 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk

```

**Comment by BYK** [comment]
>Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'

This tells you the error: you have a problem with your DNS.

Closing as this is not something we can solve on our side. Feel free to keep the conversation going over at [the forum](https://forum.sentry.io)

**Comment by caugner** [comment]
@BYK Thank you for the hint.

It looks like the following lead to the my issues:

1. We had `ufw` enabled.
2. We had set `{ "iptables": false }` in `/etc/docker/daemon.json`.

This lead to connectivity issues.
