### ISSUE TITLE
Move sentry 9 data to sentry 10

### ISSUE THREAD

**Issue by Hunter-Thompson** [getsentry/onpremise#506]
I created a new server, and I need to copy over the data from the old server to the new one.

I tried exporting the json file and importing it I got the following error:

```
root@a5fee8af745e:/# sentry import sentry_export.json 
14:59:39 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
14:59:42 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/backup.py", line 15, in import_
    for obj in serializers.deserialize("json", src, stream=True, use_natural_keys=True):
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 88, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 81, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
django.core.serializers.base.DeserializationError: No JSON object could be decoded
```

Is there an easy way to copy over the data from the old server?

The old server runs the `af07ad9c55183b4341c4ad49fe1009cad9dd4135` commit.

**Comment by BYK** [comment]
Are you trying to upgrade (which you can do in-place by simply running `./install.sh` with the latest version of this repo checked out) or migrate to a new server?

**Comment by Hunter-Thompson** [comment]
> Are you trying to upgrade (which you can do in-place by simply running `./install.sh` with the latest version of this repo checked out) or migrate to a new server?

I am trying to migrate to a new server.

**Comment by BYK** [comment]
@Hunter-Thompson sorry for the very late response. With the `import` and `export` functionality, you wouldn't be able to carry your event data to your new server. Also, our `import` functionality have been neglected a bit and does not work great. We are planning to change this in the coming months.



The best way to migrate would be to backup and move all the Docker volumes Sentry uses. Are you able to do this?
