### ISSUE TITLE
Snuba POST error for /tests/*?

### ISSUE THREAD

**Issue by narcoticfresh** [getsentry/onpremise#507]
Hi guys..

After using Sentry 9 for a long time, I've finally tried to upgrade our installation to Sentry 10. After a few hiccups (and many of the responses to issues in this project, thanks!); I succeeded mostly. 

In my setup, Sentry can query snuba-api correctly, but the feeding doesn't seem to work - yes, I bootstrapped snuba with `--force` as well.

One remaining issue I have now is that sentry-worker seems to be unable to feed data to snuba; I get this SnubaError:

```
SnubaError: HTTP 405 response from Snuba!
11:33:33 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[70650a98-767b-4152-aac8-4fff5724fee1] raised unexpected: SnubaError('HTTP 405 response from Snuba!',) (data={u'hostname': 'celery@8f675277c0e6', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': 'e2c767cfc3e14154938931931e9d3dca', 'cache_key': u'e:e2c767cfc3e14154938931931e9d3dca:7', 'start_time': 1590147213.113794, 'project_id': 7L, 'data': None}", u'id': '70650a98-767b-4152-aac8-4fff5724fee1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 169, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 164, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 794, in save_event
    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 760, in _do_save_event
    project_id, assume_normalized=True, start_time=start_time, cache_key=cache_key
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 193, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 645, in save
    _eventstream_insert_many(jobs)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 193, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 934, in _eventstream_insert_many
    skip_consume=job.get("raw", False),
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 288, in insert
    skip_consume,
  File "/usr/local/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 132, in insert
    headers={"Received-Timestamp": six.text_type(received_timestamp)},
  File "/usr/local/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 261, in _send
    raise snuba.SnubaError("HTTP %s response from Snuba!" % resp.status)
```

After checking the [relevant python source in snuba.py](https://github.com/getsentry/sentry/blob/76d48b85bdb58f708bceffb318e2d92a7091973c/src/sentry/eventstream/snuba.py#L252-L261) I've noticed that Sentry wants to do a POST to snuba at `/tests/*/eventstream`.

My question is: Is that a misconfiguration/missing something somewhere? Or could this be a problem within Sentry itself? I don't think that snuba has a /tests/ endpoint?

I didn't want to post this issue on getsentry/sentry directly as I'm sure they will first asked me if I work with onpremise then (propably) send me over here anyway..?

My sentry version is 10.1.0.dev017788bd - all using latest images where possible as of today..

Thanks very much for any hints!

**Comment by BYK** [comment]
Can you share your `sentry.conf.py` file with us?

**Comment by narcoticfresh** [comment]
@BYK

Yes, sure.. here you go..

And yes, I must admit it's a bit of a mess - we had this file based on Sentry 9 that read things nicely from ENV variables.. so i tried to port over most things added in Sentry 10 and added support for ENV handling - most notably Kafka and snuba configurations..

I'm not really educated how those variables defined here correlate to the stuff in the server initializer, so maybe I could drop and/or simplify a lot. 

But my key case was that I didn't want to switch many of those settings into the YAML file as I want to have ENV var support..

Do you spot any obvious problems/missing things? 

Thanks for your time!

```
########## IMPORTANT BASE FILE
# SEE https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py

# This file is just Python, with a touch of Django which means
# you can inherit and tweak settings to your hearts content.

# For Docker, the following environment variables are supported:
#  SENTRY_POSTGRES_HOST
#  SENTRY_POSTGRES_PORT
#  SENTRY_DB_NAME
#  SENTRY_DB_USER
#  SENTRY_DB_PASSWORD
#  SENTRY_RABBITMQ_HOST
#  SENTRY_RABBITMQ_USERNAME
#  SENTRY_RABBITMQ_PASSWORD
#  SENTRY_RABBITMQ_VHOST
#  SENTRY_REDIS_HOST
#  SENTRY_REDIS_PASSWORD
#  SENTRY_REDIS_PORT
#  SENTRY_REDIS_DB
#  SENTRY_MEMCACHED_HOST
#  SENTRY_MEMCACHED_PORT
#  SENTRY_FILESTORE_DIR
#  SENTRY_SERVER_EMAIL
#  SENTRY_EMAIL_HOST
#  SENTRY_EMAIL_PORT
#  SENTRY_EMAIL_USER
#  SENTRY_EMAIL_PASSWORD
#  SENTRY_EMAIL_USE_TLS
#  SENTRY_ENABLE_EMAIL_REPLIES
#  SENTRY_SMTP_HOSTNAME
#  SENTRY_MAILGUN_API_KEY
#  SENTRY_SINGLE_ORGANIZATION
#  SENTRY_SECRET_KEY
#  (slack integration)
#  SENTRY_SLACK_CLIENT_ID
#  SENTRY_SLACK_CLIENT_SECRET
#  SENTRY_SLACK_VERIFICATION_TOKEN
#  (github plugin, sso)
#  GITHUB_APP_ID
#  GITHUB_API_SECRET
#  (github integration)
#  SENTRY_GITHUB_APP_ID
#  SENTRY_GITHUB_APP_CLIENT_ID
#  SENTRY_GITHUB_APP_CLIENT_SECRET
#  SENTRY_GITHUB_APP_WEBHOOK_SECRET
#  SENTRY_GITHUB_APP_PRIVATE_KEY
#  (azure devops integration)
#  SENTRY_VSTS_CLIENT_ID
#  SENTRY_VSTS_CLIENT_SECRET
#  (bitbucket plugin)
#  BITBUCKET_CONSUMER_KEY
#  BITBUCKET_CONSUMER_SECRET
from sentry.conf.server import *  # NOQA
from sentry.utils.types import Bool, Int

import os
import os.path
import six

CONF_ROOT = os.path.dirname(__file__)

postgres = env('SENTRY_POSTGRES_HOST') or (env('POSTGRES_PORT_5432_TCP_ADDR') and 'postgres')
if postgres:
    DATABASES = {
        'default': {
            'ENGINE': 'sentry.db.postgres',
            'NAME': (
                env('SENTRY_DB_NAME')
                or env('POSTGRES_ENV_POSTGRES_USER')
                or 'postgres'
            ),
            'USER': (
                env('SENTRY_DB_USER')
                or env('POSTGRES_ENV_POSTGRES_USER')
                or 'postgres'
            ),
            'PASSWORD': (
                env('SENTRY_DB_PASSWORD')
                or env('POSTGRES_ENV_POSTGRES_PASSWORD')
                or ''
            ),
            'HOST': postgres,
            'PORT': (
                env('SENTRY_POSTGRES_PORT')
                or ''
            ),
            'OPTIONS': {
                'autocommit': True,
            },
        },
    }

# You should not change this setting after your database has been created
# unless you have altered all schemas first
SENTRY_USE_BIG_INTS = True

# If you're expecting any kind of real traffic on Sentry, we highly recommend
# configuring the CACHES and Redis settings

###########
# General #
###########

# Instruct Sentry that this install intends to be run by a single organization
# and thus various UI optimizations should be enabled.
SENTRY_SINGLE_ORGANIZATION = env('SENTRY_SINGLE_ORGANIZATION', True)

###########
# GITHUB OAUTH #
###########

#GITHUB_APP_ID = env('SENTRY_GITHUB_APP_ID') or ''
#GITHUB_APP_ID = int(env('SENTRY_GITHUB_APP_ID')) or 0
#GITHUB_API_SECRET = env('SENTRY_GITHUB_API_SECRET') or ''
#GITHUB_REQUIRE_VERIFIED_EMAIL = True

#########
# Redis #
#########

# Generic Redis configuration used as defaults for various things including:
# Buffers, Quotas, TSDB

redis = env('SENTRY_REDIS_HOST') or (env('REDIS_PORT_6379_TCP_ADDR') and 'redis')
if not redis:
    raise Exception('Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?')

redis_password = env('SENTRY_REDIS_PASSWORD') or ''
redis_port = env('SENTRY_REDIS_PORT') or '6379'
redis_db = env('SENTRY_REDIS_DB') or '0'

SENTRY_OPTIONS.update({
    'redis.clusters': {
        'default': {
            'hosts': {
                0: {
                    'host': redis,
                    'password': redis_password,
                    'port': redis_port,
                    'db': redis_db,
                },
            },
        },
    },
})

#########
# Cache #
#########

# Sentry currently utilizes two separate mechanisms. While CACHES is not a
# requirement, it will optimize several high throughput patterns.

memcached = env('SENTRY_MEMCACHED_HOST') or (env('MEMCACHED_PORT_11211_TCP_ADDR') and 'memcached')
if memcached:
    memcached_port = (
        env('SENTRY_MEMCACHED_PORT')
        or '11211'
    )
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': [memcached + ':' + memcached_port],
            'TIMEOUT': 3600,
        }
    }

# A primary cache is required for things such as processing events
SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

kafka_port = (
    env('SENTRY_KAFKA_PORT')
    or '9092'
)

DEFAULT_KAFKA_OPTIONS = {
    "bootstrap.servers": env('SENTRY_KAFKA_HOST') + ":" + kafka_port,
    "message.max.bytes": 50000000,
    "socket.timeout.ms": 1000,
}

SENTRY_EVENTSTREAM = "sentry.eventstream.kafka.KafkaEventStream"
SENTRY_EVENTSTREAM_OPTIONS = {"producer_configuration": DEFAULT_KAFKA_OPTIONS}

KAFKA_CLUSTERS["default"] = DEFAULT_KAFKA_OPTIONS

#########
# Queue #
#########

# See https://docs.getsentry.com/on-premise/server/queue/ for more
# information on configuring your queue broker and workers. Sentry relies
# on a Python framework called Celery to manage queues.

rabbitmq = env('SENTRY_RABBITMQ_HOST') or (env('RABBITMQ_PORT_5672_TCP_ADDR') and 'rabbitmq')

if rabbitmq:
    BROKER_URL = (
        'amqp://' + (
            env('SENTRY_RABBITMQ_USERNAME')
            or env('RABBITMQ_ENV_RABBITMQ_DEFAULT_USER')
            or 'guest'
        ) + ':' + (
            env('SENTRY_RABBITMQ_PASSWORD')
            or env('RABBITMQ_ENV_RABBITMQ_DEFAULT_PASS')
            or 'guest'
        ) + '@' + rabbitmq + '/' + (
            env('SENTRY_RABBITMQ_VHOST')
            or env('RABBITMQ_ENV_RABBITMQ_DEFAULT_VHOST')
            or '/'
        )
    )
else:
    BROKER_URL = 'redis://:' + redis_password + '@' + redis + ':' + redis_port + '/' + redis_db


###############
# Rate Limits #
###############

# Rate limits apply to notification handlers and are enforced per-project
# automatically.

SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'

##################
# Update Buffers #
##################

# Buffers (combined with queueing) act as an intermediate layer between the
# database and the storage API. They will greatly improve efficiency on large
# numbers of the same events being sent to the API in a short amount of time.
# (read: if you send any kind of real data to Sentry, you should enable buffers)

SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'

##########
# Quotas #
##########

# Quotas allow you to rate limit individual projects or the Sentry install as
# a whole.

SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'

########
# TSDB #
########

# The TSDB is used for building charts as well as making things like per-rate
# alerts possible.

#SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'
SENTRY_TSDB = "sentry.tsdb.redissnuba.RedisSnubaTSDB"

#########
# SNUBA #
#########

SENTRY_SEARCH = "sentry.search.snuba.EventsDatasetSnubaSearchBackend"

#SENTRY_SEARCH_OPTIONS = {}
#SENTRY_SEARCH_OPTIONS = {
#    'urls': ['http://' + env('SENTRY_SNUBA_HOST') + ':1218/'],
#    'timeout': 5,
#}
SENTRY_TAGSTORE_OPTIONS = {}

# Snuba configuration
SENTRY_SNUBA = os.environ.get("SNUBA", "http://"+env('SENTRY_SNUBA_HOST')+":1218")

###########
# Digests #
###########

# The digest backend powers notification summaries.

SENTRY_DIGESTS = 'sentry.digests.backends.redis.RedisBackend'

################
# File storage #
################

# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.

SENTRY_OPTIONS['filestore.backend'] = 'filesystem'
SENTRY_OPTIONS['filestore.options'] = {
    'location': env('SENTRY_FILESTORE_DIR'),
}

##############
# Web Server #
##############

# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and set `SENTRY_USE_SSL=1`

if env('SENTRY_USE_SSL', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

SENTRY_WEB_HOST = '0.0.0.0'
SENTRY_WEB_PORT = 9000
SENTRY_WEB_OPTIONS = {
    # 'workers': 3,  # the number of web workers
}

SENTRY_FEATURES["projects:sample-events"] = False
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:discover-basic",
            "organizations:discover-query",
            "organizations:events-v2",
            "organizations:global-views",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )
    }
)

##########
# Docker #
##########

# Docker's environment configuration needs to happen
# prior to anything that might rely on these values to
# enable more "smart" configuration.

ENV_CONFIG_MAPPING = {
    'SENTRY_EMAIL_PASSWORD': 'mail.password',
    'SENTRY_EMAIL_USER': 'mail.username',
    'SENTRY_EMAIL_PORT': ('mail.port', Int),
    'SENTRY_EMAIL_USE_TLS': ('mail.use-tls', Bool),
    'SENTRY_EMAIL_HOST': 'mail.host',
    'SENTRY_SERVER_EMAIL': 'mail.from',
    'SENTRY_ENABLE_EMAIL_REPLIES': 'mail.enable-replies',
    'SENTRY_SMTP_HOSTNAME': 'mail.reply-hostname',
    'SENTRY_SECRET_KEY': 'system.secret-key',

    'SENTRY_FULL_URL': 'system.url-prefix',
    'SENTRY_ADMIN_EMAIL': 'system.admin-email',

    # If you're using mailgun for inbound mail, set your API key and configure a
    # route to forward to /api/hooks/mailgun/inbound/
    'SENTRY_MAILGUN_API_KEY': 'mail.mailgun-api-key',

    'SENTRY_SLACK_CLIENT_ID': 'slack.client-id',
    'SENTRY_SLACK_CLIENT_SECRET': 'slack.client-secret',
    'SENTRY_SLACK_VERIFICATION_TOKEN': 'slack.verification-token',

    'SENTRY_GITHUB_APP_ID': ('github-app.id', Int),
    'SENTRY_GITHUB_APP_CLIENT_ID': 'github-app.client-id',
    'SENTRY_GITHUB_APP_CLIENT_SECRET': 'github-app.client-secret',
    'SENTRY_GITHUB_APP_WEBHOOK_SECRET': 'github-app.webhook-secret',
    'SENTRY_GITHUB_APP_PRIVATE_KEY': 'github-app.private-key',

    'SENTRY_VSTS_CLIENT_ID': 'vsts.client-id',
    'SENTRY_VSTS_CLIENT_SECRET': 'vsts.client-secret',
}


def bind_env_config(config=SENTRY_OPTIONS, mapping=ENV_CONFIG_MAPPING):
    """
    Automatically bind SENTRY_OPTIONS from a set of environment variables.
    """
    for env_var, item in six.iteritems(mapping):
        # HACK: we need to check both in `os.environ` and `env._cache`.
        # This is very much an implementation detail leaking out
        # due to assumptions about how `env` would be used previously.
        # `env` will pop values out of `os.environ` when they are seen,
        # so checking against `os.environ` only means it's likely
        # they won't exist if `env()` has been called on the variable
        # before at any point. So we're choosing to check both, but this
        # behavior is different since we're trying to only conditionally
        # apply variables, instead of setting them always.
        if env_var not in os.environ and env_var not in env._cache:
            continue
        if isinstance(item, tuple):
            opt_key, type_ = item
        else:
            opt_key, type_ = item, None
        config[opt_key] = env(env_var, type=type_)

# If this value ever becomes compromised, it's important to regenerate your
# SENTRY_SECRET_KEY. Changing this value will result in all current sessions
# being invalidated.
secret_key = env('SENTRY_SECRET_KEY')
if not secret_key:
    raise Exception('Error: SENTRY_SECRET_KEY is undefined, run `generate-secret-key` and set to -e SENTRY_SECRET_KEY')

if 'SENTRY_RUNNING_UWSGI' not in os.environ and len(secret_key) < 32:
    print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
    print('!!                    CAUTION                       !!')
    print('!! Your SENTRY_SECRET_KEY is potentially insecure.  !!')
    print('!!    We recommend at least 32 characters long.     !!')
    print('!!     Regenerate with `generate-secret-key`.       !!')
    print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')

# Grab the easy configuration first - these are all fixed
# key=value with no logic behind them
bind_env_config()

# If you specify a MAILGUN_API_KEY, you definitely want EMAIL_REPLIES
if SENTRY_OPTIONS.get('mail.mailgun-api-key'):
    SENTRY_OPTIONS.setdefault('mail.enable-replies', True)

if 'GITHUB_APP_ID' in os.environ:
    GITHUB_EXTENDED_PERMISSIONS = ['repo']
    GITHUB_APP_ID = env('GITHUB_APP_ID')
    GITHUB_API_SECRET = env('GITHUB_API_SECRET')

if 'BITBUCKET_CONSUMER_KEY' in os.environ:
    BITBUCKET_CONSUMER_KEY = env('BITBUCKET_CONSUMER_KEY')
    BITBUCKET_CONSUMER_SECRET = env('BITBUCKET_CONSUMER_SECRET')
```

**Comment by BYK** [comment]
```
File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/eventstream/snuba.py", line 288, in insert
    skip_consume,
```

This part suggests that you are using the deprecated `SnubaEventStream` for `SENTRY_EVENTSTREAM` while your config shows that it is set to the new (and correct) `sentry.eventstream.kafka.KafkaEventStream`. Are you sure your instances are using the latest config properly?

**Comment by narcoticfresh** [comment]
@BYK 
Thanks for your input..

well, my config was a mess.. i now used the new `sentry.conf.py` from this repo as a base and added some `env()` calls..

i still don't really understand how sentry parses ENV variables itself.. it would be really nice to have more documentation for onpremise.. but I understand they want to push their hosted business, which is makes sense I guess ;-/

--> so my installation works now, thanks!

by the way, what confused me: in [`docker-compose.yml` the ENV `SENTRY_CONF` is set to `/etc/sentry`](https://github.com/getsentry/onpremise/blob/83160e8bdbebfea2c0f02849b545b9cf1b30c324/docker-compose.yml#L23-L25), *but* in the [`Dockerfile`, config resources are copied to `/usr/src/sentry`](https://github.com/getsentry/onpremise/blob/83160e8bdbebfea2c0f02849b545b9cf1b30c324/sentry/Dockerfile#L5) - I don't know if maybe Sentry never found my old config. So in my Dockerfile, I now copy the config resources (yaml and sentry.conf.py) to /etc/sentry - now it works. So I'm not sure if it was my messed config or the wrong location :smile:

**Comment by BYK** [comment]
@narcoticfresh glad you got it working!

>i still don't really understand how sentry parses ENV variables itself..

There is _some_ env variable parsing done in https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py but we really push for putting everything into the config file yourself.

>it would be really nice to have more documentation for onpremise.. but I understand they want to push their hosted business, which is makes sense I guess ;-/

Sorry to hear that as we are definitely not pushing for SaaS 🙂 My full-time job at Sentry is to make sure on-premise works, is recent, and has proper documentation. Your feedback regarding docs are definitely valid and right now we are in the process of some pruning and shuffling. We'll be having more and up-to-date docr for on-premise in the coming months.

>by the way, what confused me: in docker-compose.yml the ENV SENTRY_CONF is set to /etc/sentry, but in the Dockerfile, config resources are copied to /usr/src/sentry - I don't know if maybe Sentry never found my old config. So in my Dockerfile, I now copy the config resources (yaml and sentry.conf.py) to /etc/sentry - now it works. So I'm not sure if it was my messed config or the wrong location 😄

If you look carefully, you'd notice that

1. There's a [`.dockerignore` file](https://github.com/getsentry/onpremise/blob/83160e8bdbebfea2c0f02849b545b9cf1b30c324/sentry/.dockerignore) in that directory that only allows copying of `requirements.txt`.
2. The `sentry` directory containing the config files is [mounted as a volume to `/etc/sentry`](https://github.com/getsentry/onpremise/blob/83160e8bdbebfea2c0f02849b545b9cf1b30c324/docker-compose.yml#L28) so no need to copy things in and your old config was most probably read 🙂
