### ISSUE TITLE
Sentry onpremise install crashes after some point of time 

### ISSUE THREAD

**Issue by poojapmagar** [getsentry/onpremise#541]
Log Start

```
Checking minimum requirements...
Removing network onpremise_default
Network onpremise_default not found.
Stopping sentry_onpremise_snuba-replacer_1          ... 

Stopping sentry_onpremise_snuba-consumer_1          ... 

Stopping sentry_onpremise_snuba-sessions-consumer_1 ... 

Stopping sentry_onpremise_snuba-outcomes-consumer_1 ... 

Stopping sentry_onpremise_snuba-api_1               ... 

Stopping sentry_onpremise_memcached_1               ... 

Stopping sentry_onpremise_symbolicator_1            ... 

Stopping sentry_onpremise_postgres_1                ... 

Stopping sentry_onpremise_smtp_1                    ... 

Stopping sentry_onpremise_kafka_1                   ... 

Stopping sentry_onpremise_zookeeper_1               ... 

Stopping sentry_onpremise_clickhouse_1              ... 

Stopping sentry_onpremise_redis_1                   ... 

Stopping sentry_onpremise_smtp_1                    ... done

Stopping sentry_onpremise_postgres_1                ... done

Stopping sentry_onpremise_memcached_1               ... done

Stopping sentry_onpremise_snuba-replacer_1          ... done

Stopping sentry_onpremise_symbolicator_1            ... done

Stopping sentry_onpremise_snuba-consumer_1          ... done

Stopping sentry_onpremise_snuba-sessions-consumer_1 ... done

Stopping sentry_onpremise_snuba-outcomes-consumer_1 ... done

Stopping sentry_onpremise_snuba-api_1               ... done

Stopping sentry_onpremise_redis_1                   ... done

Stopping sentry_onpremise_clickhouse_1              ... done

Stopping sentry_onpremise_kafka_1                   ... done

Stopping sentry_onpremise_zookeeper_1               ... done

Removing sentry_onpremise_snuba-replacer_1          ... 

Removing sentry_onpremise_snuba-consumer_1          ... 

Removing sentry_onpremise_snuba-sessions-consumer_1 ... 

Removing sentry_onpremise_snuba-outcomes-consumer_1 ... 

Removing sentry_onpremise_snuba-api_1               ... 

Removing sentry_onpremise_memcached_1               ... 

Removing sentry_onpremise_symbolicator_1            ... 

Removing sentry_onpremise_postgres_1                ... 

Removing sentry_onpremise_smtp_1                    ... 

Removing sentry_onpremise_kafka_1                   ... 

Removing sentry_onpremise_zookeeper_1               ... 

Removing sentry_onpremise_clickhouse_1              ... 

Removing sentry_onpremise_redis_1                   ... 

Removing sentry_onpremise_snuba-api_1               ... done

Removing sentry_onpremise_snuba-consumer_1          ... done

Removing sentry_onpremise_smtp_1                    ... done

Removing sentry_onpremise_postgres_1                ... done

Removing sentry_onpremise_symbolicator_1            ... done

Removing sentry_onpremise_clickhouse_1              ... done

Removing sentry_onpremise_snuba-replacer_1          ... done

Removing sentry_onpremise_zookeeper_1               ... done

Removing sentry_onpremise_snuba-sessions-consumer_1 ... done

Removing sentry_onpremise_snuba-outcomes-consumer_1 ... done

Removing sentry_onpremise_redis_1                   ... done

Removing sentry_onpremise_kafka_1                   ... done

Removing sentry_onpremise_memcached_1               ... done

Removing network sentry_onpremise_default

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.

Fetching and updating Docker images...

Some service image(s) must be built from source by running:
    docker-compose build snuba-cleanup worker cron symbolicator-cleanup post-process-forwarder web ingest-consumer sentry-cleanup
latest: Pulling from getsentry/sentry
Digest: sha256:d484f88d0a36201bddbbe380dced05349543d8c4f451527b910fcc51cdbf4fca
Status: Image is up to date for getsentry/sentry:latest
docker.io/getsentry/sentry:latest

Building and tagging Docker images...

Building web
Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGE
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}
 ---> bb490d2c6526
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> e8bb8c0c7b8e
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 73e9bb4601a2

Successfully built 73e9bb4601a2
Successfully tagged sentry-onpremise-local:latest
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
symbolicator uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup          ... 

Building symbolicator-cleanup   ... 

Building web                    ... 

Building cron                   ... 

Building worker                 ... 

Building ingest-consumer        ... 

Building post-process-forwarder ... 

Building sentry-cleanup         ... 

Building web
Building snuba-cleanup
Building post-process-forwarder
Building cron
Building symbolicator-cleanup
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> d6cf0be44380
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> ffed92e15ba2
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 16ac65915fe6
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> d578b386e40e

Successfully built d578b386e40e
Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGEStep 1/5 : ARG SENTRY_VERSION=latest

Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}Step 2/5 : ARG SENTRY_IMAGE

 ---> bb490d2c6526
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}Step 4/5 : COPY . /usr/src/sentry

 ---> Using cache
 ---> e8bb8c0c7b8e
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 73e9bb4601a2

Successfully built 73e9bb4601a2
 ---> bb490d2c6526
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> e8bb8c0c7b8e
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 73e9bb4601a2

Successfully built 73e9bb4601a2
Successfully tagged symbolicator-cleanup-onpremise-local:latest
Successfully tagged sentry-onpremise-local:latest
Building cron                   ... done

Building ingest-consumer
Building symbolicator-cleanup   ... done

Building sentry-cleanup
Successfully tagged sentry-onpremise-local:latest
Building web                    ... done

Building worker
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 58474bae6693
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGE
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}
 ---> bb490d2c6526
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9ba26e8331f4
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> Using cache
 ---> e8bb8c0c7b8e
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> 6fdd532962f3
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> Using cache
 ---> 73e9bb4601a2

Successfully built 73e9bb4601a2
 ---> bae3f770be12

Successfully built bae3f770be12
Successfully tagged sentry-onpremise-local:latest
Successfully tagged snuba-cleanup-onpremise-local:latest
Building post-process-forwarder ... done

Building snuba-cleanup          ... done

Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGE
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}
 ---> bb490d2c6526
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> e8bb8c0c7b8e
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 73e9bb4601a2

Successfully built 73e9bb4601a2
Successfully tagged sentry-onpremise-local:latest
Building ingest-consumer        ... done

Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 73e9bb4601a2
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 46b6d0465439
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> ddaa655c76e3
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> ee150fdd998d

Successfully built ee150fdd998d
Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGE
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}
Successfully tagged sentry-cleanup-onpremise-local:latest
 ---> bb490d2c6526
Step 4/5 : COPY . /usr/src/sentry
Building sentry-cleanup         ... done

 ---> Using cache
 ---> e8bb8c0c7b8e
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 73e9bb4601a2

Successfully built 73e9bb4601a2
Successfully tagged sentry-onpremise-local:latest
Building worker                 ... done


Docker images built.
Creating network "sentry_onpremise_default" with the default driver
Bootstrapping and migrating Snuba...
Creating sentry_onpremise_zookeeper_1 ... 

Creating sentry_onpremise_redis_1     ... 

Creating sentry_onpremise_clickhouse_1 ... 

Creating sentry_onpremise_zookeeper_1  ... done

Creating sentry_onpremise_kafka_1      ... 

Creating sentry_onpremise_redis_1      ... done

Creating sentry_onpremise_clickhouse_1 ... done

Creating sentry_onpremise_kafka_1      ... done

+ '[' b = - ']'
+ snuba bootstrap --help
+ set -- snuba bootstrap --force
+ set gosu snuba snuba bootstrap --force
+ exec gosu snuba snuba bootstrap --force
2020-06-15 12:34:22,575 Connection to Kafka failed (attempt 0)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 56, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2020-06-15 12:34:24,578 Connection to Kafka failed (attempt 1)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 56, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2020-06-15 12:34:26,581 Connection to Kafka failed (attempt 2)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 56, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2020-06-15 12:34:28,064 Failed to create topic cdc
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'cdc' already exists."}
2020-06-15 12:34:28,065 Failed to create topic events
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'events' already exists."}
2020-06-15 12:34:28,066 Failed to create topic ingest-sessions
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'ingest-sessions' already exists."}
2020-06-15 12:34:28,066 Failed to create topic outcomes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'outcomes' already exists."}
2020-06-15 12:34:28,067 Failed to create topic event-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'event-replacements' already exists."}
2020-06-15 12:34:28,067 Failed to create topic snuba-commit-log
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'snuba-commit-log' already exists."}
2020-06-15 12:34:28,068 Failed to create topic errors-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 92, in bootstrap
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'errors-replacements' already exists."}
2020-06-15 12:34:28,093 Creating tables for storage events
2020-06-15 12:34:28,102 Migrating storage events
2020-06-15 12:34:28,190 Creating tables for storage errors
2020-06-15 12:34:28,196 Migrating storage errors
2020-06-15 12:34:28,248 Creating tables for storage groupedmessages
2020-06-15 12:34:28,250 Migrating storage groupedmessages
2020-06-15 12:34:28,264 Creating tables for storage groupassignees
2020-06-15 12:34:28,266 Migrating storage groupassignees
2020-06-15 12:34:28,280 Creating tables for storage outcomes_raw
2020-06-15 12:34:28,284 Migrating storage outcomes_raw
2020-06-15 12:34:28,298 Creating tables for storage outcomes_hourly
2020-06-15 12:34:28,301 Migrating storage outcomes_hourly
2020-06-15 12:34:28,308 Creating tables for storage sessions_raw
2020-06-15 12:34:28,310 Migrating storage sessions_raw
2020-06-15 12:34:28,322 Creating tables for storage sessions_hourly
2020-06-15 12:34:28,330 Migrating storage sessions_hourly
2020-06-15 12:34:28,345 Creating tables for storage transactions
2020-06-15 12:34:28,350 Migrating storage transactions


Setting up database...
Creating sentry_onpremise_smtp_1 ... 

Creating sentry_onpremise_postgres_1 ... 

Starting sentry_onpremise_clickhouse_1 ... 

Starting sentry_onpremise_redis_1      ... 

Starting sentry_onpremise_clickhouse_1 ... done

Creating sentry_onpremise_symbolicator_1 ... 

Starting sentry_onpremise_redis_1        ... done

Starting sentry_onpremise_zookeeper_1    ... 

Creating sentry_onpremise_memcached_1    ... 

Starting sentry_onpremise_zookeeper_1    ... done

Starting sentry_onpremise_kafka_1        ... 

Starting sentry_onpremise_kafka_1        ... done

Creating sentry_onpremise_snuba-sessions-consumer_1 ... 

Creating sentry_onpremise_snuba-replacer_1          ... 

Creating sentry_onpremise_snuba-api_1               ... 

Creating sentry_onpremise_snuba-consumer_1          ... 

Creating sentry_onpremise_snuba-outcomes-consumer_1 ... 

Creating sentry_onpremise_smtp_1                    ... done

Creating sentry_onpremise_symbolicator_1            ... done

Creating sentry_onpremise_postgres_1                ... done

Creating sentry_onpremise_memcached_1               ... done

Creating sentry_onpremise_snuba-sessions-consumer_1 ... done

Creating sentry_onpremise_snuba-outcomes-consumer_1 ... done

Creating sentry_onpremise_snuba-replacer_1          ... done

Creating sentry_onpremise_snuba-consumer_1          ... done

Creating sentry_onpremise_snuba-api_1               ... done

12:34:40 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
12:34:47 [INFO] sentry.plugins.github: apps-not-configured
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter

Generating Relay credentials...
error: could not open config file (file /work/C:/Users/<userName>/AppData/Local/Temp/config.yml)
  caused by: No such file or directory (os error 2)
Cleaning up...
```
Log End 

Can anyone tell me which doc to refer for proper customization no references for "/work/C:/Users/" suspecting /work is creating issue but not sure why i'm facing this issue have kept on trying for couple of time please help me out

**Comment by BYK** [comment]
Looks like your `$(pwd)` command returns an incorrect path. Could you be using Cygwin?

**Comment by BYK** [comment]
@poojapmagar do you still need help with this?

**Comment by BYK** [comment]
Closing due to lack of response.

**Comment by ydwis40** [comment]
Hello I have same problem. I'm using gitbash for windows.

**Comment by BYK** [comment]
@ydwis40 please try WSL if you are on Windows. Git-Bash or Cygwin are not supported.
