### ISSUE TITLE
Sentry on prem 400 response status codes with relay

### ISSUE THREAD

**Issue by mitchfriedman** [getsentry/onpremise#590]
Hi, we have setup a relay service and we are trying to forward events to our on-prem sentry installation.

When sending test events (sentry-cli send-event -m 'A test event'), we see errors in relay logs like:

```
dropped event: could not send event to upstream
  caused by: upstream request returned error 400 Bad Request
```

and then when inspecting the logs on the sentry-web process, I see: 
```
Traceback (most recent call last):                                                                                                                                                                                      
File "/usr/local/lib/python2.7/site-packages/sentry/coreapi.py", line 308, in safely_load_json_string                                                                                                                 
obj = json.loads(json_string)                                                                                                                                                                                       
File "/usr/local/lib/python2.7/site-packages/sentry/utils/json.py", line 107, in loads 
return _default_decoder.decode(value)
File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 373, in decoderaise JSONDecodeError("Extra data", s, end, len(s))
JSONDecodeError: Extra data: line 2 column 1 - line 4 column 1 (char 273 - 6049) 
```

We were previously going straight to sentry, and if I run the same command with the $SENTRY_DSN set to sentry, it works a s expected.

**Comment by BYK** [comment]
Hi @mitchfriedman - we have removed the event ingestion endpoint from Sentry in https://github.com/getsentry/sentry/commit/fdba72bd7c96f6b340c5d3e2cc7439f61f400020 and from that point on, the new Relay + Nginx setup is required for event ingestion to work.

We do not support third-party helm or k8s integrations so you'd better raise the issue up there for them to keep their repo in sync with our setup here on getsentry/onpremise.
