### ISSUE TITLE
Relay messages don't make it through

### ISSUE THREAD

**Issue by jeremyherbert** [getsentry/onpremise#606]
Hi,

I'm using a modified install in kubernetes. I am having trouble getting events to pass through a relay to the platform, and I'm not able to find any errors anywhere in the logs (even with DEBUG/TRACE logging enabled). It seems to get to the relay and then doesn't get much further than that. This is the log from the relay:

```
DEBUG relay_server::actors::upstream > got register challenge (token = -_qn1iG2zdEB8KqfgGVXQtfoHfmIvWMOgHhk55KMEOzvK9h03kvfTVQ9QetFIIlinIE1KAQRvGjvLZiywVy_9g)
DEBUG relay_server::actors::upstream > sending register challenge response
DEBUG relay_server::actors::upstream > relay successfully registered with upstream

...

DEBUG relay_server::actors::project > project 7 state requested
TRACE relay_server::actors::events > queued event
DEBUG relay_server::actors::project > project 7 state request amended
DEBUG relay_server::actors::project_upstream > updating project states for 1/1 projects (attempt 1)
DEBUG relay_server::actors::project_upstream > sending request of size 1
DEBUG relay_server::actors::project > project 7 state updated
TRACE relay_server::actors::events > processing json event
TRACE relay_server::actors::events > sending envelope to kafka
TRACE relay_server::actors::store > Sending event item of envelope to kafka
```

But there are no logs of this in Kafka (I am not 100% sure there should be though?); all I have is this over and over

```
[2020-07-22 05:33:54,379] DEBUG Got ping response for sessionid: 0x10000009a5e0017 after 0ms (org.apache.zookeeper.ClientCnxn)
```

The celery worker doesn't give any clues either, the only thing I see is this:

```
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.check_auth[7b220370-e2e1-4702-97a1-5e7697ef5b19] expires:[2020-07-22 05:36:21.125839+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.check_auth', '7b220370-e2e1-4702-97a1-5e7697ef5b19', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'auth', u'exchange': 'default'}, 'expires': '2020-07-22T05:36:21.125839+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.check_auth', 'callbacks': None, u'correlation_id': '7b220370-e2e1-4702-97a1-5e7697ef5b19', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': '7b220370-e2e1-4702-97a1-5e7697ef5b19', u'headers': {}}) kwargs:{})
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.check_auth[7b220370-e2e1-4702-97a1-5e7697ef5b19] pid:33
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.check_monitors[bbcd88a1-95a4-4cf6-98b1-14effd1eb013] expires:[2020-07-22 05:36:21.128754+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.check_monitors', 'bbcd88a1-95a4-4cf6-98b1-14effd1eb013', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'default', u'exchange': 'default'}, 'expires': '2020-07-22T05:36:21.128754+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.check_monitors', 'callbacks': None, u'correlation_id': 'bbcd88a1-95a4-4cf6-98b1-14effd1eb013', 'errbacks': None, 'timelimit': (15, 10), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': 'bbcd88a1-95a4-4cf6-98b1-14effd1eb013', u'headers': {}}) kwargs:{})
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.check_monitors[bbcd88a1-95a4-4cf6-98b1-14effd1eb013] pid:28
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.check_auth[7b220370-e2e1-4702-97a1-5e7697ef5b19] succeeded in 0.0053511809997s: None
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.enqueue_scheduled_jobs[38988ff5-2270-4be8-aa51-3544e3fee7c3] expires:[2020-07-22 05:36:21.132627+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.enqueue_scheduled_jobs', '38988ff5-2270-4be8-aa51-3544e3fee7c3', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'default', u'exchange': 'default'}, 'expires': '2020-07-22T05:36:21.132627+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.enqueue_scheduled_jobs', 'callbacks': None, u'correlation_id': '38988ff5-2270-4be8-aa51-3544e3fee7c3', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': '38988ff5-2270-4be8-aa51-3544e3fee7c3', u'headers': {}}) kwargs:{})
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.enqueue_scheduled_jobs[38988ff5-2270-4be8-aa51-3544e3fee7c3] pid:34
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.send_ping[c0685029-f200-4958-8a95-510e499541c0] expires:[2020-07-22 05:36:21.135724+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.send_ping', 'c0685029-f200-4958-8a95-510e499541c0', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'default', u'exchange': 'default'}, 'expires': '2020-07-22T05:36:21.135724+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.send_ping', 'callbacks': None, u'correlation_id': 'c0685029-f200-4958-8a95-510e499541c0', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': 'c0685029-f200-4958-8a95-510e499541c0', u'headers': {}}) kwargs:{})
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
return self.registry[key]
KeyError: 'sentry:last_worker_ping'
05:35:21 [DEBUG] sentry: Using legacy key: sentry:last_worker_ping
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.send_ping[c0685029-f200-4958-8a95-510e499541c0] pid:30
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.check_monitors[bbcd88a1-95a4-4cf6-98b1-14effd1eb013] succeeded in 0.0103826949999s: None
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.enqueue_scheduled_jobs[38988ff5-2270-4be8-aa51-3544e3fee7c3] succeeded in 0.00622906300032s: None
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
return self.registry[key]
KeyError: 'sentry:last_worker_version'
05:35:21 [DEBUG] sentry: Using legacy key: sentry:last_worker_version
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.send_ping[c0685029-f200-4958-8a95-510e499541c0] succeeded in 0.0120896230001s: None
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.digests.schedule_digests[7167b9e2-df7c-40f7-93c3-f78c2c17e92c] expires:[2020-07-22 05:35:51.159370+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.digests.schedule_digests', '7167b9e2-df7c-40f7-93c3-f78c2c17e92c', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'digests.scheduling', u'exchange': 'default'}, 'expires': '2020-07-22T05:35:51.159370+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.digests.schedule_digests', 'callbacks': None, u'correlation_id': '7167b9e2-df7c-40f7-93c3-f78c2c17e92c', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': '7167b9e2-df7c-40f7-93c3-f78c2c17e92c', u'headers': {}}) kwargs:{})
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.digests.schedule_digests[7167b9e2-df7c-40f7-93c3-f78c2c17e92c] pid:24
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.digests.schedule_digests[7167b9e2-df7c-40f7-93c3-f78c2c17e92c] succeeded in 0.00235998100015s: None
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.process_buffer.process_pending[9cb2211c-1fd9-46ba-bdb3-25b2c2e483ca] expires:[2020-07-22 05:35:31.240166+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.process_buffer.process_pending', '9cb2211c-1fd9-46ba-bdb3-25b2c2e483ca', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'buffers.process_pending', u'exchange': 'default'}, 'expires': '2020-07-22T05:35:31.240166+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.process_buffer.process_pending', 'callbacks': None, u'correlation_id': '9cb2211c-1fd9-46ba-bdb3-25b2c2e483ca', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': '9cb2211c-1fd9-46ba-bdb3-25b2c2e483ca', u'headers': {}}) kwargs:{})
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.process_buffer.process_pending[9cb2211c-1fd9-46ba-bdb3-25b2c2e483ca] pid:25
05:35:21 [INFO] celery.worker.strategy: Received task: sentry.tasks.options.sync_options[df79f0b4-c782-4f79-b8ea-16b640fd3cf3] expires:[2020-07-22 05:35:31.244636+00:00]
05:35:21 [DEBUG] celery.pool: TaskPool: Apply <function _fast_trace_task at 0x7f7c0de56488> (args:('sentry.tasks.options.sync_options', 'df79f0b4-c782-4f79-b8ea-16b640fd3cf3', [], {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': [], 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'options', u'exchange': 'default'}, 'expires': '2020-07-22T05:35:31.244636+00:00', u'hostname': 'celery@sentry-worker-6fdd7687bf-dkvck', 'task': 'sentry.tasks.options.sync_options', 'callbacks': None, u'correlation_id': 'df79f0b4-c782-4f79-b8ea-16b640fd3cf3', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': 'b9054d59-bd79-3911-a815-e5cb1a3f6d22', 'id': 'df79f0b4-c782-4f79-b8ea-16b640fd3cf3', u'headers': {}}) kwargs:{})
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.process_buffer.process_pending[9cb2211c-1fd9-46ba-bdb3-25b2c2e483ca] succeeded in 0.00407671899984s: None
05:35:21 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.options.sync_options[df79f0b4-c782-4f79-b8ea-16b640fd3cf3] pid:31
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
return self.registry[key]
KeyError: u'sentry:last_worker_ping'
05:35:21 [DEBUG] sentry: Using legacy key: sentry:last_worker_ping
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
return self.registry[key]
KeyError: u'sentry:last_worker_version'
05:35:21 [DEBUG] sentry: Using legacy key: sentry:last_worker_version
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
return self.registry[key]
KeyError: u'sentry:version-configured'
05:35:21 [DEBUG] sentry: Using legacy key: sentry:version-configured
05:35:21 [INFO] celery.worker.job: Task sentry.tasks.options.sync_options[df79f0b4-c782-4f79-b8ea-16b640fd3cf3] succeeded in 0.00547905700023s: None
```

The snuba and zookeeper logs show nothing interesting.

Could someone please help point me in the right direction with this? 

I am using getsentry/sentry:2614c3d32bac4acbe23025e78a6218f624c53d15 which is the latest version at the time of writing. I also had the issue with 20.7.2.

**Comment by HCrane** [comment]
Hey Jeremy! I am currently in the process setting up onpremise in openshift. Could you maybe share your kubernetes yaml files?

**Comment by jeremyherbert** [comment]
@HCrane I would, but I don't know how to export them (I'm doing everything in the Rancher web interface). Also, it doesn't work yet ;)

I have made a tiny bit of progress here, digging through the kafka logs I see that the ingested error is indeed showing up, so it seems that perhaps the kafka consumer is not hooked up correctly.

**Comment by BYK** [comment]
Please make sure you have all the consumers listed here with up-to-date configs:

https://github.com/getsentry/onpremise/blob/4dbfcbcebe9d7ea54bd009bb85a331dc6ef51295/docker-compose.yml#L109-L126

We have changed some parameters there due to changes in Snuba so I'm guessing that's your issue.

Also, closing this issue as this is not related to the repo and [the forum](https://forum.sentry.io) is a better place to discuss custom on-premise solutions and issues.
