### ISSUE TITLE
send mail error

### ISSUE THREAD

**Issue by uncode** [getsentry/onpremise#67]
```
web_1        | 118.186.200.10 - - [11/Dec/2017:15:33:35 +0000] "POST /api/2/store/ HTTP/1.1" 200 366 "-" "sentry-php/1.8.1"
postgres_1   | ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
postgres_1   | DETAIL:  Key (project_id, environment_id)=(2, 1) already exists.
postgres_1   | STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id") VALUES (2, 1) RETURNING "sentry_environmentproject"."id"
worker_1     | 15:33:35 [INFO] sentry.plugins.mail: notification.dispatched (project_id=2L plugin=u'mail' event_id=29L group_id=8L rule_id=2L digest_key=u'mail:p:2')
worker_1     | 15:33:37 [INFO] sentry.mail: mail.queued (message_to=(u'mail@lishunqi.com',) event_id=29L group_id=8L message_type=u'notify.error' message_id=u'<20171211153336.19.25341@localhost>')




worker_1     | celery@2af3bcee7361 ready.
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
worker_1     |     R = retval = fun(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1     |     return self.run(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
worker_1     |     result = func(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 76, in send_email
worker_1     |     send_messages([message])
worker_1     |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 416, in send_messages
worker_1     |     sent = connection.send_messages(messages)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
worker_1     |     new_conn_created = self.open()
worker_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 48, in open
worker_1     |     local_hostname=DNS_NAME.get_fqdn())
worker_1     |   File "/usr/local/lib/python2.7/smtplib.py", line 256, in __init__
worker_1     |     (code, msg) = self.connect(host, port)
worker_1     |   File "/usr/local/lib/python2.7/smtplib.py", line 318, in connect
worker_1     |     (code, msg) = self.getreply()
worker_1     |   File "/usr/local/lib/python2.7/smtplib.py", line 366, in getreply
worker_1     |     + str(e))
worker_1     | SMTPServerDisconnected: Connection unexpectedly closed: timed out
worker_1     | 15:33:42 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[6b60ad32-fcf4-4994-ad41-b490b4b753d3] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed: timed out',) (data={u'hostname': 'celery@2af3bcee7361', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f58e2d50a90>}", u'id': '6b60ad32-fcf4-4994-ad41-b490b4b753d3'})

```

**Comment by uncode** [comment]
why celery use `celery@2af3bcee7361` ?

```
worker_1     | 15:33:42 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[6b60ad32-fcf4-4994-ad41-b490b4b753d3] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed: timed out',) (data={u'hostname': 'celery@2af3bcee7361', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f58e2d50a90>}", u'id': '6b60ad32-fcf4-4994-ad41-b490b4b753d3'})
```

**Comment by Narayanan170** [comment]
@uncode Did you resolve this?
