### ISSUE TITLE
Ingest Consumer crashing over file permissions

### ISSUE THREAD

**Issue by davjr96** [getsentry/onpremise#679]
## Version Information

Version: Sentry 20.10.0.dev08dc4efa

## Description

sentry_onpremise_ingest-consumer_1 keeps crashing and appears to fail at file creation.

## Steps to Reproduce

Startup container

## Logs

Please share any applicable logs:

`
18:39:20 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
18:39:24 [INFO] sentry.plugins.github: apps-not-configured
18:39:27 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=ingest-attachments,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-transactions,partition=0,offset=-1001,error=None}]
18:39:28 [INFO] batching-kafka-consumer: Flushing 21 items (from {(u'ingest-attachments', 0): [6L, 11L], (u'ingest-events', 0): [28258L, 28262L], (u'ingest-transactions', 0): [3641L, 3650L]}): forced:False size:False time:True
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 440, in ingest_consumer
    get_ingest_consumer(consumer_types=consumer_types, **options).run()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 212, in run
    self._run_once()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 217, in _run_once
    self._flush()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/batching_kafka_consumer.py", line 333, in _flush
    self.worker.flush_batch(self.__batch_results)
  File "/usr/local/lib/python2.7/site-packages/sentry/ingest/ingest_consumer.py", line 44, in flush_batch
    return self._flush_batch(batch)
  File "/usr/local/lib/python2.7/site-packages/sentry/ingest/ingest_consumer.py", line 83, in _flush_batch
    processing_func(message, projects=projects)
  File "/usr/local/lib/python2.7/site-packages/sentry/ingest/ingest_consumer.py", line 97, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 193, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/ingest/ingest_consumer.py", line 240, in process_individual_attachment
    start_time=None,  # TODO: Inject this from Relay
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 1300, in save_attachment
    file.putfile(six.BytesIO(data), blob_size=settings.SENTRY_ATTACHMENT_BLOB_SIZE)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 388, in putfile
    blob = FileBlob.from_file(blob_fileobj, logger=logger)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 248, in from_file
    storage.save(blob.path, fileobj)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 321, in _save
    os.makedirs(directory)
  File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/files'
`

**Comment by davjr96** [comment]
Running `docker exec -it  sentry_onpremise_ingest-consumer_1 chmod -R 777 /opt` works as a workaround

**Comment by BYK** [comment]
Our default path for storing files is `/data/files` where we mount the `sentry-data` volume to. Could you have changed that somehow and forgot to mount the volume there?

**Comment by davjr96** [comment]
Ah you're right, somehow my config was pointing to opt, I don't remember changing it and it has been working for a while...

Thanks!
