### ISSUE TITLE
Unknown field found while parsing JSONEachRow format: message_timestamp

### ISSUE THREAD

**Issue by fnkr** [getsentry/onpremise#700]
### Old

getsentry/onpremise commit: dffd59723c05eb7a8a13f441a6cbb8b4e85fc437

Docker Images:

```
$ sudo docker ps -q | xargs sudo docker container inspect | jq -r '.[] | .Name + " \t " + .Image' | expand -t 24
/sentry_onpremise_web_1                          sha256:6a5429fe46ca769c208834e3e441d0c0ca3d9cbb69ba476be306fdba65866ae6
/sentry_onpremise_post-process-forwarder_1       sha256:6a5429fe46ca769c208834e3e441d0c0ca3d9cbb69ba476be306fdba65866ae6
/sentry_onpremise_sentry-cleanup_1               sha256:7ac006eb463162535833fc9c110ce798f17139db41aa95486e636a993bcb8a55
/sentry_onpremise_worker_1                       sha256:6a5429fe46ca769c208834e3e441d0c0ca3d9cbb69ba476be306fdba65866ae6
/sentry_onpremise_cron_1                         sha256:6a5429fe46ca769c208834e3e441d0c0ca3d9cbb69ba476be306fdba65866ae6
/sentry_onpremise_snuba-api_1                    sha256:87a9fa9963ac811449df358b1c3a4a0c67f4d0d4eaaa26874c52fc6888baefc5
/sentry_onpremise_snuba-replacer_1               sha256:87a9fa9963ac811449df358b1c3a4a0c67f4d0d4eaaa26874c52fc6888baefc5
/sentry_onpremise_snuba-cleanup_1                sha256:d01af2beb9341bf12a035248451972103612b6728246fda0cd5c8b1cebfdd1d8
/sentry_onpremise_snuba-consumer_1               sha256:87a9fa9963ac811449df358b1c3a4a0c67f4d0d4eaaa26874c52fc6888baefc5
/sentry_onpremise_kafka_1                        sha256:163b44d95ebe47a0d43ae79036c2fe1cf72c7ff76ec1cf14baa5ef984c53214c
/sentry_onpremise_symbolicator_1                 sha256:8aa085e331458303c371f4ddce75cd361ea88007ed609fbe65a83acb5736958e
/sentry_onpremise_memcached_1                    sha256:0dbf6b4c454b48d353be6a6bb19c9fb5fc693cd1e78a2e2f6ae77dbe43d2549e
/sentry_onpremise_nginx_1                        sha256:2073e0bcb60ee98548d313ead5eacbfe16d9054f8800a32bedd859922a99a6e1
/sentry_onpremise_symbolicator-cleanup_1         sha256:7ee56f48f98bd3ba23db5b6512a40116983a3122322baf75ebde79b76ce554e4
/sentry_onpremise_zookeeper_1                    sha256:5d4b53b8289761f237ace35192023cee16eb71346cd605868eb9bbeff0724629
/sentry_onpremise_postgres_1                     sha256:cb2889ab0680ba518e0dc1bb5a09cbe23f1e5908d9e484daea3d34f5e092ec17
/sentry_onpremise_smtp_1                         sha256:81d26a0a35d8cbfb6fd232bbf7c0a7a015698e4083ec94d14daffb55ac0586be
/sentry_onpremise_redis_1                        sha256:b68707e68547e636f2544e9283f02beed46d536f644573c8b35c368f9abbe078
/sentry_onpremise_clickhouse_1                   sha256:3a157c707b61323f1caaad9b1ff52e69eb316f782f8bd4ce1ee5109b09458a5a
```

### New

getsentry/onpremise: 3408e3db99a946e5b7850a845a53894951a276f4

Docker Images:

```
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
symbolicator-cleanup-onpremise-local   latest              31848fd4b184        3 hours ago         174MB
sentry-cleanup-onpremise-local         latest              fdea02b49c18        3 hours ago         906MB
snuba-cleanup-onpremise-local          latest              66b0ba034631        3 hours ago         392MB
sentry-onpremise-local                 latest              a27e36322b27        3 hours ago         904MB
getsentry/sentry                       latest              4826135605b7        23 hours ago        904MB
getsentry/snuba                        latest              9516004eac76        23 hours ago        391MB
getsentry/relay                        latest              fde3069a8aa5        33 hours ago        197MB
getsentry/symbolicator                 latest              90d421cda48c        5 days ago          173MB
postgres                               9.6                 22280012ef4a        2 weeks ago         200MB
tianon/exim4                           latest              8381f6d6214a        4 weeks ago         176MB
busybox                                latest              6858809bf669        4 weeks ago         1.23MB
redis                                  5.0-alpine          893bb508e38f        2 months ago        30.3MB
alpine                                 latest              a24bb4013296        4 months ago        5.57MB
yandex/clickhouse-server               20.3.9.70           abe55fc6544d        4 months ago        497MB
nginx                                  1.16                dfcfd8e9a5d3        5 months ago        127MB
confluentinc/cp-kafka                  5.5.0               89e8e98718a8        5 months ago        598MB
confluentinc/cp-zookeeper              5.5.0               124ff6469e3d        5 months ago        598MB
memcached                              1.5-alpine          0dbf6b4c454b        8 months ago        9.19MB
```

## Description

After upgrading from an older version, event processing does not work anymore:

```
snuba.clickhouse.errors.ClickhouseWriterError: [117] Unknown field found while parsing JSONEachRow format: message_timestamp: (at row 1)
```

## Steps to Reproduce

1. Upgrade from old to new version
2. Try to process events

I already tried applying snuba migrations (was recommended here https://github.com/getsentry/snuba/issues/760) but it didn't help:

```
docker-compose run --rm snuba-api migrations migrate --force
```

## Logs

```
nginx_1                        | 172.19.0.1 - a2b9b3b958cb45adbeca13ac0da23f73 [10/Oct/2020:22:12:53 +0000] "POST /api/15/store/ HTTP/1.0" 200 41 "-" "Go-http-client/2.0" "-"
ingest-consumer_1              | 22:12:54 [INFO] batching-kafka-consumer: Flushing 1 items (from {(u'ingest-events', 0): [48L, 48L]}): forced:False size:False time:True
ingest-consumer_1              | 22:12:54 [INFO] batching-kafka-consumer: Worker flush took 15ms
snuba-transactions-consumer_1  | 2020-10-10 22:12:55,422 Completed processing <Batch: 1 message, open for 1.01 seconds>.
snuba-consumer_1               | 2020-10-10 22:12:55,437 Caught ClickhouseWriterError(code=117, message='Unknown field found while parsing JSONEachRow format: message_timestamp: (at row 1)', row=1), shutting down...
snuba-outcomes-consumer_1      | 2020-10-10 22:12:55,437 Completed processing <Batch: 1 message, open for 1.02 seconds>.
snuba-consumer_1               | Traceback (most recent call last):
snuba-consumer_1               |   File "/usr/local/bin/snuba", line 33, in <module>
snuba-consumer_1               |     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
snuba-consumer_1               |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
snuba-consumer_1               |     return self.main(*args, **kwargs)
snuba-consumer_1               |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
snuba-consumer_1               |     rv = self.invoke(ctx)
snuba-consumer_1               |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
snuba-consumer_1               |     return _process_result(sub_ctx.command.invoke(sub_ctx))
snuba-consumer_1               |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
snuba-consumer_1               |     return ctx.invoke(self.callback, **ctx.params)
snuba-consumer_1               |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
snuba-consumer_1               |     return callback(*args, **kwargs)
snuba-consumer_1               |   File "/usr/src/snuba/snuba/cli/consumer.py", line 173, in consumer
snuba-consumer_1               |     consumer.run()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 109, in run
snuba-consumer_1               |     self._run_once()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 144, in _run_once
snuba-consumer_1               |     self.__processing_strategy.poll()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/transform.py", line 56, in poll
snuba-consumer_1               |     self.__next_step.poll()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 122, in poll
snuba-consumer_1               |     self.__close_and_reset_batch()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 104, in __close_and_reset_batch
snuba-consumer_1               |     self.__batch.close()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 64, in close
snuba-consumer_1               |     self.__step.close()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/consumer.py", line 310, in close
snuba-consumer_1               |     self.__insert_batch_writer.close()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/consumer.py", line 183, in close
snuba-consumer_1               |     self.__writer.write(
snuba-consumer_1               |   File "/usr/src/snuba/snuba/clickhouse/http.py", line 175, in write
snuba-consumer_1               |     batch.join()
snuba-consumer_1               |   File "/usr/src/snuba/snuba/clickhouse/http.py", line 129, in join
snuba-consumer_1               |     raise ClickhouseWriterError(code, message, row)
snuba-consumer_1               | snuba.clickhouse.errors.ClickhouseWriterError: [117] Unknown field found while parsing JSONEachRow format: message_timestamp: (at row 1)
sentry_onpremise_snuba-consumer_1 exited with code 1
snuba-outcomes-consumer_1      | 2020-10-10 22:12:57,346 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
snuba-sessions-consumer_1      | 2020-10-10 22:12:57,380 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)]
snuba-outcomes-consumer_1      | 2020-10-10 22:12:57,388 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 4411766}
snuba-sessions-consumer_1      | 2020-10-10 22:12:57,437 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 0}
snuba-consumer_1               | + set -- snuba consumer --storage events --auto-offset-reset=latest --max-batch-time-ms 750
snuba-consumer_1               | + set gosu snuba snuba consumer --storage events --auto-offset-reset=latest --max-batch-time-ms 750
snuba-consumer_1               | + exec gosu snuba snuba consumer --storage events --auto-offset-reset=latest --max-batch-time-ms 750
snuba-outcomes-consumer_1      | 2020-10-10 22:13:00,345 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
snuba-sessions-consumer_1      | 2020-10-10 22:13:00,395 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)]
snuba-outcomes-consumer_1      | 2020-10-10 22:13:00,403 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 4411766}
snuba-consumer_1               | 2020-10-10 22:13:00,405 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 2840193}
snuba-sessions-consumer_1      | 2020-10-10 22:13:00,453 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 0}
```

**Comment by BYK** [comment]
>Upgrade from old to new version

What is your upgrade procedure? Can you share your upgrade logs as requested in the issue template please?

**Comment by BYK** [comment]
Also seeing this `/sentry_onpremise_mattermost-hook-bridge_1` suggests that you have some modifications. I recommend making sure you get the latest updates from the docker-compose file and the example configurations.

**Comment by fnkr** [comment]
I tried the migration again today using the latest release of getsentry/sentry and getsentry/onpremise. This time it did work. Probably I did something wrong the first time (or the issue has been fixed meanwhile). Thanks anyway, and sorry for the noise :)
