### ISSUE TITLE
request failure on 20.11.0

### ISSUE THREAD

**Issue by omaraltayyan** [getsentry/onpremise#742]
## Version Information

Version: 20.11.0

## Description

i am receiving an error on every request we make after updating from 20.10.1 to 20.11.0

## Steps to Reproduce

1. update sentry to 20.11.0
2. wait for docker containers to start and be stable
3. make any request

## Logs

```
web_1                                       | Traceback (most recent call last):
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 124, in handle_exception
web_1                                       |     response = super(Endpoint, self).handle_exception(exc)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
web_1                                       |     self.raise_uncaught_exception(exc)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 237, in dispatch
web_1                                       |     response = handler(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_details.py", line 435, in get
web_1                                       |     context = serialize(organization, request.user, serializer(), access=request.access)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 19, in serialize
web_1                                       |     return serialize([objects], user=user, serializer=serializer, **kwargs)[0]
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 45, in serialize
web_1                                       |     return [serializer(o, attrs=attrs.get(o, {}), user=user, **kwargs) for o in objects]
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 60, in __call__
web_1                                       |     return self.serialize(obj, attrs, user, **kwargs)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/organization.py", line 356, in serialize
web_1                                       |     context["projects"] = serialize(project_list, user, ProjectSummarySerializer())
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 41, in serialize
web_1                                       |     **kwargs
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 426, in get_attrs
web_1                                       |     for release in bulk_fetch_project_latest_releases(item_list)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 513, in bulk_fetch_project_latest_releases
web_1                                       |     (tuple(six.text_type(i.id) for i in projects),),
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1259, in __iter__
web_1                                       |     instance = model_cls.from_db(db, model_init_names, model_init_values)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 583, in from_db
web_1                                       |     new = cls(*values)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 48, in __init__
web_1                                       |     self._update_tracked_data()
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 90, in _update_tracked_data
web_1                                       |     v = self.__get_field_value(f)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 76, in __get_field_value
web_1                                       |     return getattr(self, field.attname, None)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query_utils.py", line 116, in __get__
web_1                                       |     instance.refresh_from_db(fields=[self.field_name])
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 691, in refresh_from_db
web_1                                       |     db_instance_qs = db_instance_qs.only(*fields)
web_1                                       |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 74, in only
web_1                                       |     raise NotImplementedError("Use ``values_list`` instead [performance].")
web_1                                       | NotImplementedError: Use ``values_list`` instead [performance].
nginx_1                                     | ** - - [17/Nov/2020:14:41:39 +0000] "GET /api/0/organizations/**/?detailed=1 HTTP/1.1" 500 72 "https://**/settings/account/details/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36" "**"

```

NOTE: i marked our own identifiers with `**`

**Comment by BYK** [comment]
Can you try restarting `memcached`: `docker-compose restart memcached`

**Comment by omaraltayyan** [comment]
> Can you try restarting `memcached`: `docker-compose restart memcached`

I tried restarting with `docker-compose restart` a few times with no effect, does restarting only this container have a different effect?

**Comment by omaraltayyan** [comment]
I'd like to add that reverting to 20.10.1 solved the issue so it must be something in the code not something stuck in a container state

**Comment by BYK** [comment]
@omaraltayyan not necessarily. Can you share your upgrade logs?

**Comment by omaraltayyan** [comment]
@BYK for some reason updating to 20.11.1 **solved my issue**


these are the commands i used:

```
git pull
git checkout 20.11.1
SENTRY_IMAGE=getsentry/sentry:20.11.1 ./install.sh
docker-compose up -d
```

**Comment by BYK** [comment]
Thanks for reporting back @omaraltayyan! I checked the diff between the two releases and nothing seemed related to this issue so I'll just assume your caches expired or some migration was not completed properly in your previous upgrade.

Let us know if you bump into any issues in the next release please.

**Comment by omaraltayyan** [comment]
> Thanks for reporting back @omaraltayyan! I checked the diff between the two releases and nothing seemed related to this issue so I'll just assume your caches expired or some migration was not completed properly in your previous upgrade.
> 
> Let us know if you bump into any issues in the next release please.

yes that's likely it, thanks for your awesome effort and amazing platform!!
