### ISSUE TITLE
Kafka uses too much disk space

### ISSUE THREAD

**Issue by erfansahaf** [getsentry/onpremise#757]
## Version Information

Version: 20.10.1

## Description

I notified by the monitoring system that the sentry server is running out of disk space. After checking sentry containers, I found out that Kafka is using around ~450 GB o disk space and that's why the disk got full!

- Why did this happen?
- Why Kafka should consume this much disk space?
- How can I clean it up?

## Steps to Reproduce

1. Keep sending errors to your sentry projects.

## Logs

I had to bring the containers down so I could free a bit of disk space to be able to work with the system. Before happening this problem, everything was working fine, and no errors were seen.

**Comment by BYK** [comment]
Found some useful info here: https://stackoverflow.com/a/52970982/90297

I'll check how much of this is applicable. //cc @chadwhitacre

**Comment by erfansahaf** [comment]
Is there any way to clean these logs so I can bring the stack up?

**Comment by BYK** [comment]
@erfansahaf I think if we/you set some of those variables and restart the Kafka container, it should clean this itself?

**Comment by erfansahaf** [comment]
After cleaning up the Kafka, Sentry doesn't accept/process new events. Kafka throws an exception: `Broker: Offset out of range`

Here is the log:

```
post-process-forwarder_1       | 08:07:17 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
post-process-forwarder_1       | /usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
post-process-forwarder_1       |   from cryptography import x509
post-process-forwarder_1       | 08:07:21 [INFO] sentry.plugins.github: apps-not-configured
post-process-forwarder_1       | Traceback (most recent call last):
post-process-forwarder_1       |   File "/usr/local/bin/sentry", line 8, in <module>
post-process-forwarder_1       |     sys.exit(main())
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
post-process-forwarder_1       |     cli(prog_name=get_prog(), obj={}, max_content_width=100)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
post-process-forwarder_1       |     return self.main(*args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 782, in main
post-process-forwarder_1       |     rv = self.invoke(ctx)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
post-process-forwarder_1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
post-process-forwarder_1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
post-process-forwarder_1       |     return ctx.invoke(self.callback, **ctx.params)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
post-process-forwarder_1       |     return callback(*args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
post-process-forwarder_1       |     return f(get_current_context(), *args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 68, in inner
post-process-forwarder_1       |     return ctx.invoke(f, *args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
post-process-forwarder_1       |     return callback(*args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
post-process-forwarder_1       |     return f(get_current_context(), *args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
post-process-forwarder_1       |     return ctx.invoke(f, *args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
post-process-forwarder_1       |     return callback(*args, **kwargs)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/run.py", line 307, in post_process_forwarder
post-process-forwarder_1       |     initial_offset_reset=options["initial_offset_reset"],
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 105, in <lambda>
post-process-forwarder_1       |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
post-process-forwarder_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/eventstream/kafka/backend.py", line 195, in run_post_process_forwarder
post-process-forwarder_1       |     raise Exception(error)
post-process-forwarder_1       | Exception: KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Broker: Offset out of range"}
```

**Comment by chadwhitacre** [comment]
@erfansahaf In that case I think we're over into https://github.com/getsentry/onpremise/issues/478. There's a workaround at https://github.com/getsentry/onpremise/issues/478#issuecomment-666254392. Want to try that out?

Closing. If you find that #478 doesn't cover your issue at this point we can reopen.
