### ISSUE TITLE
20.11.1 upgrade causes new events to be lost

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#767]
## Version Information

Version: 20.11.1

## Description

We're hitting this issue and all events are discarded and I'm not sure why this was even closed or how this can be solved with the onpremise config:

https://github.com/getsentry/snuba/issues/1527

## Logs

Please share any applicable logs:

```sh
snuba-subscription-consumer-transactions_1  | 2020-12-10 09:48:30,531 Could not construct valid time interval between MessageDetails(offset=8235638, timestamp=datetime.datetime(2020, 12, 10, 9, 48, 29, 766000)) and Message(partition=Partition(topic=Topic(name='events'), index=0), offset=8235639)!
snuba-subscription-consumer-transactions_1  | Traceback (most recent call last):
snuba-subscription-consumer-transactions_1  |   File "/usr/src/snuba/snuba/subscriptions/consumer.py", line 129, in poll
snuba-subscription-consumer-transactions_1  |     time_interval = Interval(previous_message.timestamp, message.timestamp)
snuba-subscription-consumer-transactions_1  |   File "<string>", line 5, in __init__
snuba-subscription-consumer-transactions_1  |   File "/usr/src/snuba/snuba/utils/types.py", line 67, in __post_init__
snuba-subscription-consumer-transactions_1  |     raise InvalidRangeError(self.lower, self.upper)
snuba-subscription-consumer-transactions_1  | snuba.utils.types.InvalidRangeError: (datetime.datetime(2020, 12, 10, 9, 48, 29, 766000), datetime.datetime(2020, 12, 10, 9, 48, 29, 764000))
snuba-subscription-consumer-transactions_1  | 2020-12-10 09:48:30,532 Could not construct valid time interval between MessageDetails(offset=8235640, timestamp=datetime.datetime(2020, 12, 10, 9, 48, 29, 827000)) and Message(partition=Partition(topic=Topic(name='events'), index=0), offset=8235641)!
snuba-subscription-consumer-transactions_1  | Traceback (most recent call last):
snuba-subscription-consumer-transactions_1  |   File "/usr/src/snuba/snuba/subscriptions/consumer.py", line 129, in poll
snuba-subscription-consumer-transactions_1  |     time_interval = Interval(previous_message.timestamp, message.timestamp)
snuba-subscription-consumer-transactions_1  |   File "<string>", line 5, in __init__
snuba-subscription-consumer-transactions_1  |   File "/usr/src/snuba/snuba/utils/types.py", line 67, in __post_init__
snuba-subscription-consumer-transactions_1  |     raise InvalidRangeError(self.lower, self.upper)
snuba-subscription-consumer-transactions_1  | snuba.utils.types.InvalidRangeError: (datetime.datetime(2020, 12, 10, 9, 48, 29, 827000), datetime.datetime(2020, 12, 10, 9, 48, 29, 763000))
snuba-subscription-consumer-transactions_1  | 2020-12-10 09:48:30,536 Flushing 60 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=8235580, hi=8235643)})
snuba-subscription-consumer-transactions_1  | 2020-12-10 09:48:30,536 Worker flush took 0ms
clickhouse_1                                | 2020.12.10 09:48:30.546485 [ 89 ] {2f87ae0a-3da4-4ab9-962d-7320371c064d} <Information> executeQuery: Read 14 rows, 690.00 B in 0.407 sec., 34 rows/sec., 1.66 KiB/sec.
```

**Comment by max-wittig** [comment]
Should that config be in relay?

https://github.com/getsentry/onpremise/blob/master/relay/config.example.yml

```diff
relay:
  upstream: "http://web:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} #50MB or bust
+   - {name: "message.timestamp.type", value: "LogAppendTime"}
  redis: redis://redis:6379
```

**Comment by max-wittig** [comment]
Seems to be normal again. I think we had some internal event abuse. Do you have any recommendation on how to block/limit those? We're thinking about just using Nginx rate limiting, as sentry's rate limits don't really seem to capture this usecase

**Comment by BYK** [comment]
> as sentry's rate limits don't really seem to capture this usecase

Why would you say so?
