### ISSUE TITLE
Repair sentry

### ISSUE THREAD

**Issue by sdwerwed** [getsentry/onpremise#781]
## Version Information

Version: The last git commit is 4dbfcbcebe9d7ea54bd009bb85a331dc6ef51295 from master branch, that commmit exist in 20.7.1 but the images in env are latest

## Description

I just run ./install.sh to update/repair the sentry because gosu was removed by antivirus now and containers sentry_onpremise_cron_1, sentry_onpremise_worker_1, sentry_onpremise_ingest-consumer_1, sentry_onpremise_post-process-forwarder_1, sentry_onpremise_web_1 have exit code 1, and logs say 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 799, in main
    e.show()
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 22, in show
    click.secho("!! Configuration error: %s" % six.text_type(self), file=file, fg="red")
  File "/usr/local/lib/python3.6/site-packages/click/exceptions.py", line 31, in __str__
    return self.message
AttributeError: 'ConfigurationError' object has no attribute 'message'
```

## Logs

Please share any applicable logs:

- https://gist.github.com/sdwerwed/f6cf507512595b0ac1861a805745dd4a#file-docker-compose-log
- https://gist.github.com/sdwerwed/771607222137c6e62e253bc5dcecfd4c#file-sentry-install-log

**Comment by sdwerwed** [comment]
Oh `'ConfigurationError' object has no attribute 'message'` is fixed by this https://github.com/getsentry/onpremise/pull/692/files

But there is more serious issue:
```
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'errors-replacements' already exists."}
2020-12-18 17:21:05,694 Failed to create topic outcomes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'outcomes' already exists."}
2020-12-18 17:21:05,694 Failed to create topic cdc
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'cdc' already exists."}
2020-12-18 17:21:05,694 Failed to create topic ingest-sessions
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'ingest-sessions' already exists."}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 98, in bootstrap
    Runner().run_all(force=True)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 132, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 257, in _get_pending_migrations
    raise MigrationInProgress(migration_key)
snuba.migrations.errors.MigrationInProgress: transactions: 0008_transactions_add_timestamp_index
An error occurred, caught SIGERR on line 229

```

**Comment by sdwerwed** [comment]
Also the last error was fixed by `docker-compose --no-ansi run --rm snuba-api migrations reverse --group transactions --migration-id 0008_transactions_add_timestamp_index` and now there is this error **any idea?**:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 98, in bootstrap
    Runner().run_all(force=True)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 144, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 192, in _run_migration_impl
    migration.forwards(context)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 88, in forwards
    op.execute(local=True)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 34, in execute
    connection.execute(self.format_sql())
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 82, in execute
    raise ClickhouseError(e.code, e.message) from e
snuba.clickhouse.errors.ClickhouseError: [36] DB::Exception: You must set the setting `allow_experimental_data_skipping_indices` to 1 before using data skipping indices.. Stack trace:

0. 0x559061d49524 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x559061d47e19 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x559065a1eadf ? /usr/bin/clickhouse
3. 0x5590658b4113 DB::StorageMergeTree::alter(DB::AlterCommands const&, DB::Context const&, DB::TableStructureWriteLockHolder&) /usr/bin/clickhouse
4. 0x559065413473 DB::InterpreterAlterQuery::execute() /usr/bin/clickhouse
5. 0x55906574aef6 ? /usr/bin/clickhouse
6. 0x55906574c43d DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) /usr/bin/clickhouse
7. 0x559061e2c6d4 DB::TCPHandler::runImpl() /usr/bin/clickhouse
8. 0x559061e2d1cf DB::TCPHandler::run() /usr/bin/clickhouse
9. 0x559066197604 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
10. 0x559066197de1 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
11. 0x5590667663f9 Poco::PooledThread::run() /usr/bin/clickhouse
12. 0x559066762d10 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
13. 0x559066f396a4 ? /usr/bin/clickhouse
14. 0x7f64602566db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
15. 0x7f645fd7b88f clone /lib/x86_64-linux-gnu/libc-2.27.so

An error occurred, caught SIGERR on line 229
```

**Comment by sdwerwed** [comment]
Now I did checkout `releases/20.7.1` branch, before I had commit 4dbfcbcebe9d7ea54bd009bb85a331dc6ef51295 on `master` branch. How can I **repair removed gosu**?

```
+ exec gosu snuba snuba bootstrap --force
./docker_entrypoint.sh: line 16: exec: gosu: not found
An error occurred, caught SIGERR on line 229
Cleaning up...
```

**Comment by BYK** [comment]
@sdwerwed `gosu` exists inside the container so just pulling the images and rebuilding the containers should work.

Closing this issue as this is not something we can fix. You may [use the forum](https://forum.sentry.io) if you need further help.

**Comment by sdwerwed** [comment]
Deleting all images and run docker-compose up -d --force-recreate fixed that. The antivirus was deleting the file from the local images so without clean up it was not working.
