### ISSUE TITLE
Upgrade Sentry 20.11.1 > 20.12.1

### ISSUE THREAD

**Issue by JeSappelleRoot** [getsentry/onpremise#830]
### Version Information

Version: *20.11.1*

### Steps to Reproduce

1. git clone --branch 20.12.1 https://github.com/getsentry/onpremise.git (could be the origin of the issue !, no branch 20.12.1, only a tag)
2. copy some config files with custom settings
3. ./install.sh 

### Expected Result

Smooth and fine upgrade

### Actual Result

Tonight, I upgraded our Sentry from 20.8.0 to 20.12.1. I followed instructions and I made this upgrade way : 
```
Sentry 20.8.0 > Sentry 20.9.0 ✔️ 
Sentry 20.9.0 > Sentry 20.10.0 ✔️ 
Sentry 20.10.0 > Sentry 20.10.1 ✔️ 
Sentry 20.10.1 > Sentry 20.11.0 ✔️ 
Sentry 20.11.0 > Sentry 20.11.1 ✔️ 
Sentry 20.11.1 > Sentry 20.12.1 ❌ 
```

### My configuration

On ./sentry/ folder I have 4 custom files : 
- config.yml (SMTP settings, Slack settings)
- sentry.conf.py (LDAP authentication settings with OU and group membership, Django LDAP debug)
- requirements.txt (`sentry-ldap-auth` to allow LDAP authentication)
- Dockerfile with the extra line `RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y` right after `COPY . /usr/src/sentry`

On ./nginx/ folder I have a custom nginx.conf which set nginx SSL/TLS options and listen on port 443

On ./docker-compose, I updated nginx exposed port to listen on port 443 and forward requests to port 443 as well

Unfortunately, last upgrade step give me an error
I will be able to provide more details on my configuration (**except sensitive informations**)

### Logs

```
[root@sentry2 sentry-20.11.1]# cd ../sentry-20.12.1/
[root@sentry2 sentry-20.12.1]# ./install
-bash: ./install: Is a directory
[root@sentry2 sentry-20.12.1]# ./install.sh
Checking minimum requirements...

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.
symbolicator/config.yml already exists, skipped creation.
relay/config.yml already exists, skipped creation.

Fetching and updating Docker images...

Some service image(s) must be built from source by running:
    docker-compose build snuba-cleanup web subscription-consumer-events symbolicator-cleanup sentry-cleanup worker post-process-forwarder subscription-consumer-transactions ingest-consumer cron
20.12.1: Pulling from getsentry/sentry
Digest: sha256:a61fcc629ef6ee364d21e6cb3569543247fdded31cc6e44a98c4b84de646d767
Status: Image is up to date for getsentry/sentry:20.12.1
docker.io/getsentry/sentry:20.12.1

Building and tagging Docker images...

Building web
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Successfully tagged sentry-onpremise-local:latest
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup                      ...
Building symbolicator-cleanup               ...
Building web                                ...
Building cron                               ...
Building worker                             ...
Building ingest-consumer                    ...
Building post-process-forwarder             ...
Building subscription-consumer-events       ...
Building subscription-consumer-transactions ...
Building sentry-cleanup                     ...
Building web
Building snuba-cleanup
Building subscription-consumer-events
Building symbolicator-cleanup
Building subscription-consumer-transactions
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 140929786ffa
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> d1309d974971
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> c08155955ec8
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 36fd712480c1

Successfully built 36fd712480c1
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 0e9e67a40b39
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 79df2636e1dd
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> d5bde33d75f3
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> ccde03b87601

Successfully built ccde03b87601
Successfully tagged snuba-cleanup-onpremise-local:latest
Building cron
Building snuba-cleanup                      ... done
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
Successfully tagged symbolicator-cleanup-onpremise-local:latest
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Building symbolicator-cleanup               ... done
Building worker
Successfully tagged sentry-onpremise-local:latest
Building subscription-consumer-transactions ... done
Building sentry-cleanup
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Successfully tagged sentry-onpremise-local:latest
Building post-process-forwarder
Building web                                ... done
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Successfully tagged sentry-onpremise-local:latest
Building subscription-consumer-events       ... done
Building ingest-consumer
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Successfully tagged sentry-onpremise-local:latest
Building cron                               ... done
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Successfully tagged sentry-onpremise-local:latest
Building worker                             ... done
Step 1/5 : ARG BASE_IMAGE
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
Step 2/5 : FROM ${BASE_IMAGE}
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
 ---> cc9b87509f2c
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
Step 1/6 : ARG SENTRY_IMAGE
Step 2/6 : ARG SENTRY_PYTHON2
Step 3/6 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON2:+-py2}
 ---> fd01bb63570a
Step 4/6 : COPY . /usr/src/sentry
 ---> Using cache
 ---> cb6c4874b55e
Step 5/6 : RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y
 ---> Using cache
 ---> 1a2b2de3a6ad
Step 6/6 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi ---> Using cache
Successfully tagged sentry-onpremise-local:latest

 ---> a2a27c7108dd
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 28eb21493fdb
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> cc9b87509f2c

Successfully built cc9b87509f2c
Building post-process-forwarder             ... done
Successfully tagged sentry-onpremise-local:latest
Building ingest-consumer                    ... done
 ---> Using cache
 ---> 53c7272e900e

Successfully built 53c7272e900e
Successfully tagged sentry-cleanup-onpremise-local:latest
Building sentry-cleanup                     ... done

Docker images built.
Removing network onpremise_default
Network onpremise_default not found.
Removing sentry_onpremise_snuba-replacer_1              ...
Removing sentry_onpremise_snuba-consumer_1              ...
Removing sentry_onpremise_snuba-outcomes-consumer_1     ...
Removing sentry_onpremise_snuba-api_1                   ...
Removing sentry_onpremise_snuba-sessions-consumer_1     ...
Removing sentry_onpremise_snuba-transactions-consumer_1 ...
Removing sentry_onpremise_smtp_1                        ...
Removing sentry_onpremise_postgres_1                    ...
Removing sentry_onpremise_symbolicator_1                ...
Removing sentry_onpremise_memcached_1                   ...
Removing sentry_onpremise_kafka_1                       ...
Removing sentry_onpremise_zookeeper_1                   ...
Removing sentry_onpremise_clickhouse_1                  ...
Removing sentry_onpremise_redis_1                       ...
Removing sentry_onpremise_memcached_1                   ... done
Removing sentry_onpremise_snuba-outcomes-consumer_1     ... done
Removing sentry_onpremise_redis_1                       ... done
Removing sentry_onpremise_zookeeper_1                   ... done
Removing sentry_onpremise_smtp_1                        ... done
Removing sentry_onpremise_snuba-replacer_1              ... done
Removing sentry_onpremise_snuba-api_1                   ... done
Removing sentry_onpremise_postgres_1                    ... done
Removing sentry_onpremise_snuba-transactions-consumer_1 ... done
Removing sentry_onpremise_snuba-consumer_1              ... done
Removing sentry_onpremise_symbolicator_1                ... done
Removing sentry_onpremise_kafka_1                       ... done
Removing sentry_onpremise_snuba-sessions-consumer_1     ... done
Removing sentry_onpremise_clickhouse_1                  ... done
Removing network sentry_onpremise_default
Creating network "sentry_onpremise_default" with the default driver
Bootstrapping and migrating Snuba...
Creating sentry_onpremise_redis_1 ...
Creating sentry_onpremise_zookeeper_1 ...
Creating sentry_onpremise_clickhouse_1 ...
Creating sentry_onpremise_zookeeper_1  ... done
Creating sentry_onpremise_kafka_1      ...
Creating sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_redis_1      ... done
Creating sentry_onpremise_kafka_1      ... done
+ '[' b = - ']'
+ snuba bootstrap --help
+ set -- snuba bootstrap --no-migrate --force
+ set gosu snuba snuba bootstrap --no-migrate --force
+ exec gosu snuba snuba bootstrap --no-migrate --force
%3|1611099055.776|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.26.0.5:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1611099056.775|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.26.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2021-01-19 23:30:56,775 Connection to Kafka failed (attempt 0)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1611099057.777|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.26.0.5:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1611099058.777|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.26.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2021-01-19 23:30:58,778 Connection to Kafka failed (attempt 1)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1611099059.781|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.26.0.5:9092 failed: Connection refused (after 1ms in state CONNECT)
2021-01-19 23:31:00,782 Connection to Kafka failed (attempt 2)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2021-01-19 23:31:02,051 Failed to create topic cdc
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'cdc' already exists."}
2021-01-19 23:31:02,052 Failed to create topic outcomes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'outcomes' already exists."}
2021-01-19 23:31:02,052 Failed to create topic events
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'events' already exists."}
2021-01-19 23:31:02,052 Failed to create topic errors-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'errors-replacements' already exists."}
2021-01-19 23:31:02,053 Failed to create topic ingest-sessions
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'ingest-sessions' already exists."}
2021-01-19 23:31:02,053 Failed to create topic event-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'event-replacements' already exists."}
2021-01-19 23:31:02,053 Failed to create topic snuba-commit-log
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'snuba-commit-log' already exists."}
Starting sentry_onpremise_clickhouse_1 ...
Starting sentry_onpremise_redis_1      ...
Starting sentry_onpremise_clickhouse_1 ... done
Starting sentry_onpremise_redis_1      ... done
Starting sentry_onpremise_zookeeper_1  ...
Starting sentry_onpremise_zookeeper_1  ... done
Starting sentry_onpremise_kafka_1      ...
Starting sentry_onpremise_kafka_1      ... done
+ '[' m = - ']'
+ snuba migrations --help
+ set -- snuba migrations migrate --force
+ set gosu snuba snuba migrations migrate --force
+ exec gosu snuba snuba migrations migrate --force
Finished running migrations


Setting up database...
Starting sentry_onpremise_zookeeper_1 ...
Creating sentry_onpremise_memcached_1 ...
Starting sentry_onpremise_zookeeper_1 ... done
Creating sentry_onpremise_postgres_1  ...
Creating sentry_onpremise_symbolicator_1 ...
Starting sentry_onpremise_redis_1        ...
Starting sentry_onpremise_redis_1        ... done
Starting sentry_onpremise_clickhouse_1   ...
Starting sentry_onpremise_clickhouse_1   ... done
Starting sentry_onpremise_kafka_1        ...
Creating sentry_onpremise_smtp_1         ...
Starting sentry_onpremise_kafka_1        ... done
Creating sentry_onpremise_snuba-replacer_1 ...
Creating sentry_onpremise_snuba-transactions-consumer_1 ...
Creating sentry_onpremise_snuba-outcomes-consumer_1     ...
Creating sentry_onpremise_snuba-api_1                   ...
Creating sentry_onpremise_snuba-consumer_1              ...
Creating sentry_onpremise_snuba-sessions-consumer_1     ...
Creating sentry_onpremise_memcached_1                   ... done
Creating sentry_onpremise_symbolicator_1                ... done
Creating sentry_onpremise_postgres_1                    ... done
Creating sentry_onpremise_snuba-replacer_1              ... done
Creating sentry_onpremise_smtp_1                        ... done
Creating sentry_onpremise_snuba-outcomes-consumer_1     ... done
Creating sentry_onpremise_snuba-consumer_1              ... done
Creating sentry_onpremise_snuba-api_1                   ... done
Creating sentry_onpremise_snuba-transactions-consumer_1 ... done
Creating sentry_onpremise_snuba-sessions-consumer_1     ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 46, in load_module
    mod = self._load_module(fullname)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 81, in _load_module
    load_settings(self.config_path, settings=settings_mod, silent=True)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 95, in load_settings
    six.exec_(source_file.read(), conf.__dict__)
  File "<string>", line 33, in <module>
  File "<string>", line 17, in get_internal_network
struct.error: argument for 's' must be a bytes object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 29, in inner
    configure()
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 129, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/settings.py", line 152, in configure
    hasattr(settings, "INSTALLED_APPS")
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 55, in load_module
    reraise_as(ConfigurationError(msg))
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/settings.py", line 39, in reraise_as
    six.reraise(new_type, new_exception, e_traceback)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 46, in load_module
    mod = self._load_module(fullname)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 81, in _load_module
    load_settings(self.config_path, settings=settings_mod, silent=True)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 95, in load_settings
    six.exec_(source_file.read(), conf.__dict__)
  File "<string>", line 33, in <module>
  File "<string>", line 17, in get_internal_network
sentry.runner.importer.ConfigurationError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 799, in main
    e.show()
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/importer.py", line 22, in show
    click.secho("!! Configuration error: %s" % six.text_type(self), file=file, fg="red")
  File "/usr/local/lib/python3.6/site-packages/click/exceptions.py", line 31, in __str__
    return self.message
AttributeError: 'ConfigurationError' object has no attribute 'message'
An error occurred, caught SIGERR on line 302
Cleaning up...
```

**Comment by infabo** [comment]
I had the exact same problem. Upgrade from 20.11.1 to 20.12.1 failed.

As I did no customizations in sentry/config.yml or sentry/sentry.conf.py I just deleted these so they get regenerated.

Works.

Suggest to make a diff between your config files and the example ones to find out whats happening.

**Comment by BYK** [comment]
@chadwhitacre - we may want to make the issue validation bot a bit less aggressive. I think it tripped on the extra heading @JeSappelleRoot added.

This sounds like a Py2 -> Py3 transition issue. Actually I found it: `get_internal_network` is the culprit. Since we cannot do automatic migration of config files, you need to make the necessary updates.

For this specific case, you seem to be missing this update: https://github.com/getsentry/onpremise/pull/692/files

I recommend taking the default config files and then customizing them after to make sure you have the latest updates.

Closing as this is not actionable.
