### ISSUE TITLE
CSRF Verification failed

### ISSUE THREAD

**Issue by shenggaocode** [getsentry/onpremise#904]
### Environment

 mac os

 android

How do you use Sentry?

self-hosted

Which SDK and version?

  "@sentry/react-native": "^2.3.0",

### Steps to Reproduce
1. app.js
```js
Sentry.init({
  dsn: 'https://example/72',
  environment: process.env.NODE_ENV,
  enableAutoSessionTracking: true,
});
``` 
2. android/sentry.properties
```js
defaults.url=https://example.com/
defaults.org=org
defaults.project=project
defaults.dsn=https://example/72
auth.token=token
```

### Expected Result

The crash error can properly upload, and i can see it in the sentry dashboard.

### Actual Result

the error unable to upload successfully and nothing in the sentry dashboard

What actually happened. Maybe a screenshot/recording? Maybe some logs?

```log
2021-03-26 17:23:58.995 23287-23546/com.uskid.homeapp D/Sentry: onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/com.uskid.homeapp/cache/sentry/outbox for file 30a1d86e-85cf-472b-b413-17428b34aaa7.
2021-03-26 17:23:58.997 23287-23546/com.uskid.homeapp D/Sentry: Processing Envelope with 1 item(s)
2021-03-26 17:23:59.009 23287-23287/com.uskid.homeapp D/OrientationEventListener: Orientation is:350 X:-1.0305023 Y:-6.0530396 Z:-7.760727
2021-03-26 17:23:59.053 23287-23546/com.uskid.homeapp D/Sentry: Capturing event: 8d1f0de3217448f687dca13b88254f4a
2021-03-26 17:23:59.065 23287-23287/com.uskid.homeapp D/OrientationEventListener: Orientation is:0 X:-0.015945435 Y:-6.139984 Z:-7.9505463
2021-03-26 17:23:59.065 23287-23546/com.uskid.homeapp I/Sentry: Not possible to read external files directory
2021-03-26 17:23:59.067 23287-23546/com.uskid.homeapp D/Sentry: Captured Envelope is already cached
2021-03-26 17:23:59.067 23287-23546/com.uskid.homeapp D/Sentry: Item 1 is being captured.
2021-03-26 17:23:59.124 23287-23287/com.uskid.homeapp D/OrientationEventListener: Orientation is:359 X:-0.08932495 Y:-5.5585175 Z:-7.5557404
2021-03-26 17:23:59.184 23287-23287/com.uskid.homeapp D/OrientationEventListener: Orientation is:2 X:0.18344116 Y:-5.0664062 Z:-8.32782
2021-03-26 17:23:59.185 23287-23907/com.uskid.homeapp D/Sentry: Request failed, API returned 4032021-03-26 16:26:20.270 23287-23907/com.uskid.homeapp D/Sentry: <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8">
      <meta name="robots" content="NONE,NOARCHIVE">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    
      <link href="https://sentry.smartstuddy.com/_static/1616585421/sentry/images/favicon.ico" rel="shortcut icon" type="image/png"/>
    
      <link rel="icon" href="https://sentry.smadrtstudy.com/_static/1616585421/sentry/images/icons/apple-touch-icon.png">
      <link rel="apple-touch-icon" href="https://sentry.smadrtstudy.com/_static/1616585421/sentry/images/icons/apple-touch-icon.png">
      <link rel="apple-touch-icon" sizes="76x76" href="https://sentry.smadrtstudy.com/_static/1616585421/sentry/images/icons/apple-touch-icon-76x76.png">
      <link rel="apple-touch-icon" sizes="120x120" href="https://sentry.smartdstudy.com/_static/1616585421/sentry/images/icons/apple-touch-icon-120x120.png">
      <link rel="apple-touch-icon" sizes="152x152" href="https://sentry.smartsdtudy.com/_static/1616585421/sentry/images/icons/apple-touch-icon-152x152.png">
    
      <link rel="mask-icon" sizes="any" href="https://sentry.smardtstudy.com/_static/1616585421/sentry/images/icons/sentry-glyph-black.svg" color="#FB4226">
    
      
      <link href="/_static/1616585421/sentry/dist/sentry.css" rel="stylesheet"/>
      
    
      <title>CSRF Verification Failed | Sentry</title>
    
      <script>
        window.csrfCookieName = 'sc';
        window.__sentryGlobalStaticPrefix = '/_static/1616585421/sentry/dist/';
        window.__initialData = {"privacyUrl":null,"isOnPremise":true,"features":[],"mediaUrl":"/_static/1616585421/sentry/","gravatarBaseUrl":"https://secure.gravatar.com","singleOrganization":true,"messages":[],"urlPrefix":"https://sentry.smartstdudy.com","dsn":"https://example@sentry.smartstuddy.com/1","needsUpgrade":false,"version":        window.__languageCode = "en";
      </script>
    
      
      
    
    <script>
      window.__SENTRY__OPTIONS = {
        dsn: 'https://ddd@sentry.smartstuddy.com/1',
        release: '9.1.2',
        whitelistUrls: ["*"]
      };
      window.__SENTRY__USER = {"ip_address":"33.33.33"} || undefined;
    </script>
    
      
      <script src="/_static/1616585421/sentry/dist/vendor.js"></script>
      <script src="/_static/1616585421/sentry/dist/app.js"></script>
    
      <script>
        // if the ads.js file loads below it will mark this variable as false
        window.adblockSuspected = true;
      </script>
      <script src="/_static/1616585421/sentry/js/ads.js"></script>
      
    
      
      
    </head>
    
    <body class=" narrow">
      
      <div class="app">
        
    
        
    
        
        
    <div id="blk_alerts" class="messages-container"></div>
    <script>
    $(function(){
      ReactDOM.render(React.createFactory(SentryApp.Alerts)({
         className: "alert-list"
      }), document.getElementById('blk_alerts'));
    });
    </script>
    <div id="blk_indicators"></div>
    <script>
    $(function(){
      ReactDOM.render(React.createFactory(SentryApp.Indicators)({
         className: "indicators-container"
      }), document.getElementById('blk_indicators'));
    });
    </script>
    
    
        
    
        
        
    
        
    
        <div class="container">
          
          <div class="content">
            
            
            
    <div class="pattern-bg"></div>
    <section class="org-login">
      <div class="box box-modal">
        <div class="box-header">
          
            
              
            
            <a class="logo-with-action" href="/">
              
                <span class="icon-sentry-logo-full"></span>
              
              
            </a>
          
        </div>
        <div class="box-content with-padding">
          
        <section class="body">
            <div class="page-header">
                <h2>CSRF Verification Failed</h2>
            </div>
    
            <p>A required security token was not found or was invalid.</p>
    
            <p>If you're continually seeing this issue, try the following:</p>
    
            <ol>
              <li>Clear cookies (at least for Se
2021-03-26 16:26:20.271 23287-23907/com.uskid.homeapp D/Sentry: The transport failed to send the envelope with response code 403
2021-03-26 16:26:20.271 23287-23907/com.uskid.homeapp E/Sentry: Envelope submission failed
    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:219)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-03-26 16:26:20.272 23287-23907/com.uskid.homeapp D/Sentry: Marking envelope submission result: false
2021-03-26 16:26:20.272 23287-23546/com.uskid.homeapp W/Sentry: Envelope had a failed capture at item 1. No more items will be sent.
2021-03-26 16:26:20.272 23287-23546/com.uskid.homeapp D/Sentry: File '/data/user/0/com.uskid.homeapp/cache/sentry/outbox/a93aa18c-dd99-4456-b784-67c065577e50' is done.

```

**Comment by BYK** [comment]
We'll need your self-hosted version and installation details to be able to help you with this.
