### ISSUE TITLE
Cassandra Nodestore: `Cannot downgrade protocol version below minimum supported version: 1`

### ISSUE THREAD

**Issue by craig-duffin** [getsentry/onpremise#94]
I'm attempting to set up sentry to use Cassandra as a  node store. However i'm having problems setting it up.  

I can confirm that I am able to connect to the cassandra node from the sentry worker node using cqlsh manually.

Looking at the log of the worker container I'm seeing the following when sentry attempts to communicate:
(I've removed the IP of my Cassandra node)

```
0606 10:48:01.797023   97842 cmd.go:361] log is DEPRECATED and will be removed in a future version. Use logs instead.
09:45:27 [INFO] sentry.plugins.github: apps-not-configured
09:45:28 [INFO] sentry.bgtasks: bgtask.spawn (task_name=u'sentry.bgtasks.clean_dsymcache:clean_dsymcache')

 -------------- celery@sentry-1289895001-z5cvc v3.1.18 (Cipater)
---- **** -----
--- * ***  * -- Linux-4.4.0-21-generic-x86_64-with-debian-8.10
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         sentry:0x7f2788ef7810
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> alerts           exchange=default(direct) key=alerts
                .> auth             exchange=default(direct) key=auth
                .> cleanup          exchange=default(direct) key=cleanup
                .> commits          exchange=default(direct) key=commits
                .> counters-0       exchange=counters(direct) key=
                .> default          exchange=default(direct) key=default
                .> digests.delivery exchange=default(direct) key=digests.delivery
                .> digests.scheduling exchange=default(direct) key=digests.scheduling
                .> email            exchange=default(direct) key=email
                .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
                .> events.process_event exchange=default(direct) key=events.process_event
                .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
                .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
                .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
                .> events.save_event exchange=default(direct) key=events.save_event
                .> merge            exchange=default(direct) key=merge
                .> options          exchange=default(direct) key=options
                .> reports.deliver  exchange=default(direct) key=reports.deliver
                .> reports.prepare  exchange=default(direct) key=reports.prepare
                .> search           exchange=default(direct) key=search
                .> stats            exchange=default(direct) key=stats
                .> triggers-0       exchange=triggers(direct) key=
                .> unmerge          exchange=default(direct) key=unmerge
                .> update           exchange=default(direct) key=update

09:47:09 [WARNING] cassandra.cluster: Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = set(['REDACTED']), lbp = None)
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2805, in cassandra.cluster.ControlConnection._reconnect_internal
    return self._try_connect(host)
  File "cassandra/cluster.py", line 2833, in cassandra.cluster.ControlConnection._try_connect
    self._cluster.protocol_downgrade(host.address, e.startup_version)
  File "cassandra/cluster.py", line 1233, in cassandra.cluster.Cluster.protocol_downgrade
    raise DriverException(
DriverException: Cannot downgrade protocol version below minimum supported version: 1
09:47:09 [WARNING] cassandra.cluster: [control connection] Error connecting to 10.64.76.50:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1270, in cassandra.cluster.Cluster.connect
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2773, in cassandra.cluster.ControlConnection.connect
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2816, in cassandra.cluster.ControlConnection._reconnect_internal
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'REDACTED': DriverException('Cannot downgrade protocol version below minimum supported version: 1',)})
09:47:09 [ERROR] cassandra.cluster: Control connection failed to connect, shutting down Cluster:
09:47:09 [ERROR] sentry.errors: Not capturing event due to unsafe stacktrace:
{'date': datetime.datetime(2018, 6, 6, 9, 47, 9, 621871), 'exc_info': (<class 'cassandra.cluster.NoHostAvailable'>, NoHostAvailable('Unable to connect to any servers', {'10.64.76.50': DriverException('Cannot downgrade protocol version below minimum supported version: 1',)}), <traceback object at 0x7f27806c7cb0>), 'data': {'message': u'Control connection failed to connect, shutting down Cluster:', 'sentry.interfaces.Message': {'message': u'Control connection failed to connect, shutting down Cluster:', 'params': (), 'formatted': u'Control connection failed to connect, shutting down Cluster:'}, 'logger': 'cassandra.cluster', 'level': 40}, 'stack': None, 'extra': {'thread': 139807972759296, 'process': 23, 'threadName': 'MainThread', 'filename': 'casscache.py', 'processName': 'Worker-3', 'pathname': '/usr/local/lib/python2.7/site-packages/casscache.py', 'lineno': 54}}
celery@sentry-1289895001-z5cvc ready.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/store.py", line 281, in save_event
    manager.save(project)
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 695, in save
    event.save()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 902, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 860, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 342, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/fields/node.py", line 161, in get_prep_value
    value.id = nodestore.create(value.data)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 76, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/nodestore/base.py", line 31, in create
    self.set(node_id, data)
  File "/usr/local/lib/python2.7/site-packages/sentry/nodestore/cassandra/backend.py", line 54, in set
    self.connection.set(id, data)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/cache.py", line 38, in __get__
    value = self.func(obj)
  File "/usr/local/lib/python2.7/site-packages/sentry/nodestore/cassandra/backend.py", line 41, in connection
    **self.options
  File "/usr/local/lib/python2.7/site-packages/casscache.py", line 54, in __init__
    self._session = self._cluster.connect()
  File "cassandra/cluster.py", line 1247, in cassandra.cluster.Cluster.connect
    with self._lock:
  File "cassandra/cluster.py", line 1283, in cassandra.cluster.Cluster.connect
    raise
  File "cassandra/cluster.py", line 1270, in cassandra.cluster.Cluster.connect
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2773, in cassandra.cluster.ControlConnection.connect
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2816, in cassandra.cluster.ControlConnection._reconnect_internal
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'10.64.76.50': DriverException('Cannot downgrade protocol version below minimum supported version: 1',)})
09:47:10 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[a5575c29-36d2-44e9-bc6b-be8079d3d483] raised unexpected: NoHostAvailable('Unable to connect to any servers', {'10.64.76.50': DriverException('Cannot downgrade protocol version below minimum supported version: 1',)}) (data={u'hostname': 'celery@sentry-1289895001-z5cvc', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': '14864f06e1d74539b125184a5104c69b', 'start_time': 1528278429.44644, 'cache_key': 'e:14864f06e1d74539b125184a5104c69b:1', 'data': None}", u'id': 'a5575c29-36d2-44e9-bc6b-be8079d3d483'})
```

**Comment by imcitius** [comment]
@craig-duffin did you find the solution? I'm facing the same issue.

I catch this errors in Cassandra logs, so it looks like casscahe do not send appropriate protocol fields:
```
org.apache.thrift.protocol.TProtocolException: Missing version in readMessageBegin, old client?
```

**Comment by orcswang-lang** [comment]
> @craig-duffin did you find the solution? I'm facing the same issue.
> 
> I catch this errors in Cassandra logs, so it looks like casscache do not send appropriate protocol fields:
> 
> ```
> org.apache.thrift.protocol.TProtocolException: Missing version in readMessageBegin, old client?
> ```

/usr/lib/python2.7/site-packages/casscache.py
Change self._cluster.protocol_version = 1 to self._cluster.protocol_version = 3
