### ISSUE TITLE
Events are not registered since update to v21.4

### ISSUE THREAD

**Issue by soullivaneuh** [getsentry/onpremise#944]
### Version Information

Version: 21.4.1

### Steps to Reproduce

1. Trigger an error from a project configured on Sentry

### Expected Result

I should be notified and being able to see the issue details with event.

### Actual Result

I am notified, the issue exist but:

1. It is not listed on the issues list
2. There is no event linked to the issue

![image](https://user-images.githubusercontent.com/1698357/117435109-c3e6bd00-af2d-11eb-8d98-b0498e96ea43.png)

![image](https://user-images.githubusercontent.com/1698357/117435163-d52fc980-af2d-11eb-9976-30cf481169c0.png)

### Logs

Here is the `docker-compose logs` output when an error occurs:

```
router_1                       | 10.10.251.5 - - [07/May/2021:10:07:09 +0000] "GET /api/0/issues/233/ HTTP/2.0" 200 2692 "-" "-" 1362 "sentry@docker" "http://172.23.0.26:80" 437ms
ingest-consumer_1              | 10:07:10 [INFO] batching-kafka-consumer: Flushing 4 items (from {('ingest-attachments', 0): [12, 13], ('ingest-events', 0): [1178634, 1178635]}): forced:False size:False time:True
snuba-sessions-consumer_1      | 2021-05-07 10:07:10,574 Completed processing <Batch: 4 messages, open for 1.76 seconds>.
ingest-consumer_1              | 10:07:10 [INFO] batching-kafka-consumer: Worker flush took 100ms
snuba-transactions-consumer_1  | 2021-05-07 10:07:11,876 Completed processing <Batch: 2 messages, open for 1.19 seconds>.
snuba-outcomes-consumer_1      | 2021-05-07 10:07:11,886 Completed processing <Batch: 3 messages, open for 1.32 seconds>.
snuba-consumer_1               | 2021-05-07 10:07:11,908 Completed processing <Batch: 2 messages, open for 1.22 seconds>.
```

`ls -1 sentry_install_log-*.txt | tail -1 | xargs cat`:

```
Checking minimum requirements...

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.
symbolicator/config.yml already exists, skipped creation.
relay/config.yml already exists, skipped creation.

Fetching and updating Docker images...

Some service image(s) must be built from source by running:
    docker-compose build ingest-consumer post-process-forwarder sentry-cleanup cron symbolicator-cleanup web worker snuba-cleanup
21.4.1: Pulling from getsentry/sentry
f7ec5a41d630: Already exists
6f318b7b4c32: Already exists
16da2ad15a23: Pulling fs layer
14bd3e3eee91: Pulling fs layer
e1449a280109: Pulling fs layer
8d161b0565c9: Pulling fs layer
f38f866b6e9b: Pulling fs layer
285eb28ecfa0: Pulling fs layer
314e244f9ee4: Pulling fs layer
60c31cb6691c: Pulling fs layer
3665a34f8a60: Pulling fs layer
4ff5fad08329: Pulling fs layer
ca3765436c1e: Pulling fs layer
de2fbae4e7e5: Pulling fs layer
707a5b73a7af: Pulling fs layer
8d161b0565c9: Waiting
f38f866b6e9b: Waiting
285eb28ecfa0: Waiting
314e244f9ee4: Waiting
60c31cb6691c: Waiting
3665a34f8a60: Waiting
4ff5fad08329: Waiting
ca3765436c1e: Waiting
de2fbae4e7e5: Waiting
707a5b73a7af: Waiting
14bd3e3eee91: Verifying Checksum
14bd3e3eee91: Download complete
e1449a280109: Verifying Checksum
e1449a280109: Download complete
16da2ad15a23: Verifying Checksum
16da2ad15a23: Download complete
8d161b0565c9: Verifying Checksum
8d161b0565c9: Download complete
f38f866b6e9b: Verifying Checksum
f38f866b6e9b: Download complete
285eb28ecfa0: Verifying Checksum
285eb28ecfa0: Download complete
16da2ad15a23: Pull complete
14bd3e3eee91: Pull complete
60c31cb6691c: Verifying Checksum
60c31cb6691c: Download complete
3665a34f8a60: Verifying Checksum
3665a34f8a60: Download complete
e1449a280109: Pull complete
8d161b0565c9: Pull complete
ca3765436c1e: Verifying Checksum
ca3765436c1e: Download complete
4ff5fad08329: Verifying Checksum
4ff5fad08329: Download complete
f38f866b6e9b: Pull complete
285eb28ecfa0: Pull complete
de2fbae4e7e5: Verifying Checksum
de2fbae4e7e5: Download complete
707a5b73a7af: Download complete
314e244f9ee4: Verifying Checksum
314e244f9ee4: Download complete
314e244f9ee4: Pull complete
60c31cb6691c: Pull complete
3665a34f8a60: Pull complete
4ff5fad08329: Pull complete
ca3765436c1e: Pull complete
de2fbae4e7e5: Pull complete
707a5b73a7af: Pull complete
Digest: sha256:3a213d32539701290f8eb244d0c6e849fae16ebba846a24e413f185987d6d2b5
Status: Downloaded newer image for getsentry/sentry:21.4.1
docker.io/getsentry/sentry:21.4.1

Building and tagging Docker images...

Building web
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
 ---> e2ea6046c3c1
Step 4/5 : COPY . /usr/src/sentry
 ---> 7bbb4190a3cc
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Running in a2415dbef7af
Removing intermediate container a2415dbef7af
 ---> 5537093338c3

Successfully built 5537093338c3
Successfully tagged sentry-onpremise-local:latest
router uses an image, skipping
clickhouse uses an image, skipping
smtp uses an image, skipping
postgres uses an image, skipping
redis uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
relay uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
symbolicator uses an image, skipping
memcached uses an image, skipping
snuba-replacer uses an image, skipping
snuba-consumer uses an image, skipping
snuba-api uses an image, skipping
snuba-sessions-consumer uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup          ... 
Building symbolicator-cleanup   ... 
Building web                    ... 
Building ingest-consumer        ... 
Building cron                   ... 
Building worker                 ... 
Building sentry-cleanup         ... 
Building post-process-forwarder ... 
Building worker
Building web
Building cron
Building sentry-cleanup
Building post-process-forwarder
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
 ---> e2ea6046c3c1
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 7bbb4190a3cc
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 5537093338c3

Successfully built 5537093338c3
Successfully tagged sentry-onpremise-local:latest
Building web                    ... done
Building snuba-cleanup
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
 ---> e2ea6046c3c1
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 7bbb4190a3cc
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 5537093338c3

Successfully built 5537093338c3
Successfully tagged sentry-onpremise-local:latest
Building ingest-consumer
Building worker                 ... done
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
 ---> e2ea6046c3c1
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 7bbb4190a3cc
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 5537093338c3

Successfully built 5537093338c3
Successfully tagged sentry-onpremise-local:latest
Building symbolicator-cleanup
Building cron                   ... done
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 5537093338c3
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
 ---> e2ea6046c3c1
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 7bbb4190a3cc
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 5537093338c3

Successfully built 5537093338c3
Successfully tagged sentry-onpremise-local:latest
Building post-process-forwarder ... done
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> cda5760ce0b7
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
 ---> e2ea6046c3c1
Step 4/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 7bbb4190a3cc
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 5537093338c3

Successfully built 5537093338c3
Successfully tagged sentry-onpremise-local:latest
Building ingest-consumer        ... done
 ---> Running in b7d195f32481
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 39c80d6a621c
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 0d1bc13118a5
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 8c4e25e5f37d
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 32aed4236597

Successfully built 32aed4236597
Successfully tagged symbolicator-cleanup-onpremise-local:latest
Building symbolicator-cleanup   ... done
 ---> Running in 7e43e9f6b0de
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [285 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [285 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
Fetched 8441 kB in 2s (4158 kB/s)
Reading package lists...Fetched 8441 kB in 2s (3901 kB/s)
Reading package lists...
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...

Building dependency tree...The following additional packages will be installed:
  lsb-base sensible-utils
Suggested packages:
  anacron logrotate checksecurity
Recommended packages:
  default-mta | mail-transport-agent

Reading state information...
The following NEW packages will be installed:
  cron lsb-base sensible-utils
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 143 kB of archives.
After this operation, 383 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 sensible-utils all 0.0.12 [15.8 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 lsb-base all 10.2019051400 [28.4 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 cron amd64 3.0pl1-134+deb10u1 [99.0 kB]
The following additional packages will be installed:
  lsb-base sensible-utils
Suggested packages:
  anacron logrotate checksecurity
Recommended packages:
  default-mta | mail-transport-agent
The following NEW packages will be installed:
  cron lsb-base sensible-utils
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 143 kB of archives.
After this operation, 383 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 sensible-utils all 0.0.12 [15.8 kB]
debconf: delaying package configuration, since apt-utils is not installed
Get:2 http://deb.debian.org/debian buster/main amd64 lsb-base all 10.2019051400 [28.4 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 cron amd64 3.0pl1-134+deb10u1 [99.0 kB]
Fetched 143 kB in 0s (2493 kB/s)
Selecting previously unselected package sensible-utils.
(Reading database ... 11935 files and directories currently installed.)
Preparing to unpack .../sensible-utils_0.0.12_all.deb ...
Unpacking sensible-utils (0.0.12) ...
Selecting previously unselected package lsb-base.
Preparing to unpack .../lsb-base_10.2019051400_all.deb ...
Unpacking lsb-base (10.2019051400) ...
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package cron.
Preparing to unpack .../cron_3.0pl1-134+deb10u1_amd64.deb ...
Unpacking cron (3.0pl1-134+deb10u1) ...
Fetched 143 kB in 0s (2552 kB/s)
Selecting previously unselected package sensible-utils.
(Reading database ... 6840 files and directories currently installed.)
Preparing to unpack .../sensible-utils_0.0.12_all.deb ...
Unpacking sensible-utils (0.0.12) ...
Setting up lsb-base (10.2019051400) ...
Setting up sensible-utils (0.0.12) ...
Setting up cron (3.0pl1-134+deb10u1) ...
Selecting previously unselected package lsb-base.
Preparing to unpack .../lsb-base_10.2019051400_all.deb ...
Unpacking lsb-base (10.2019051400) ...
Selecting previously unselected package cron.
Preparing to unpack .../cron_3.0pl1-134+deb10u1_amd64.deb ...
Unpacking cron (3.0pl1-134+deb10u1) ...
Adding group `crontab' (GID 101) ...
Done.
Setting up lsb-base (10.2019051400) ...
Setting up sensible-utils (0.0.12) ...
Setting up cron (3.0pl1-134+deb10u1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Adding group `crontab' (GID 101) ...
Done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container b7d195f32481
 ---> efdfd631fc0c
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
Removing intermediate container 7e43e9f6b0de
 ---> 0d048f41a45d
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> 6fc22283bdd5
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in eee2b7f2fd22
 ---> 52c961cc262f
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
Removing intermediate container eee2b7f2fd22
 ---> 4d570700e623

Successfully built 4d570700e623
Successfully tagged sentry-cleanup-onpremise-local:latest
 ---> Running in 17f6e3be16b7
Building sentry-cleanup         ... done
Removing intermediate container 17f6e3be16b7
 ---> 0ee59222ddbd

Successfully built 0ee59222ddbd
Successfully tagged snuba-cleanup-onpremise-local:latest
Building snuba-cleanup          ... done

Docker images built.
Removing network onpremise_default
Network onpremise_default not found.
Stopping sentry_onpremise_nginx_1                       ... 
Stopping sentry_onpremise_web_1                         ... 
Stopping sentry_onpremise_post-process-forwarder_1      ... 
Stopping sentry_onpremise_sentry-cleanup_1              ... 
Stopping sentry_onpremise_cron_1                        ... 
Stopping sentry_onpremise_ingest-consumer_1             ... 
Stopping sentry_onpremise_worker_1                      ... 
Stopping sentry_onpremise_snuba-cleanup_1               ... 
Stopping sentry_onpremise_relay_1                       ... 
Stopping sentry_onpremise_router_1                      ... 
Stopping sentry_onpremise_symbolicator-cleanup_1        ... 
Stopping sentry_onpremise_snuba-consumer_1              ... 
Stopping sentry_onpremise_snuba-outcomes-consumer_1     ... 
Stopping sentry_onpremise_snuba-sessions-consumer_1     ... 
Stopping sentry_onpremise_snuba-transactions-consumer_1 ... 
Stopping sentry_onpremise_snuba-replacer_1              ... 
Stopping sentry_onpremise_snuba-api_1                   ... 
Stopping sentry_onpremise_smtp_1                        ... 
Stopping sentry_onpremise_postgres_1                    ... 
Stopping sentry_onpremise_symbolicator_1                ... 
Stopping sentry_onpremise_memcached_1                   ... 
Stopping sentry_onpremise_kafka_1                       ... 
Stopping sentry_onpremise_clickhouse_1                  ... 
Stopping sentry_onpremise_redis_1                       ... 
Stopping sentry_onpremise_zookeeper_1                   ... 
Stopping sentry_onpremise_post-process-forwarder_1      ... done
Stopping sentry_onpremise_nginx_1                       ... done
Stopping sentry_onpremise_cron_1                        ... done
Stopping sentry_onpremise_ingest-consumer_1             ... done
Stopping sentry_onpremise_web_1                         ... done
Stopping sentry_onpremise_worker_1                      ... done
Stopping sentry_onpremise_relay_1                       ... done
Stopping sentry_onpremise_router_1                      ... done
Stopping sentry_onpremise_snuba-cleanup_1               ... done
Stopping sentry_onpremise_sentry-cleanup_1              ... done
Stopping sentry_onpremise_symbolicator-cleanup_1        ... done
Stopping sentry_onpremise_smtp_1                        ... done
Stopping sentry_onpremise_memcached_1                   ... done
Stopping sentry_onpremise_postgres_1                    ... done
Stopping sentry_onpremise_symbolicator_1                ... done
Stopping sentry_onpremise_snuba-outcomes-consumer_1     ... done
Stopping sentry_onpremise_snuba-sessions-consumer_1     ... done
Stopping sentry_onpremise_snuba-transactions-consumer_1 ... done
Stopping sentry_onpremise_snuba-consumer_1              ... done
Stopping sentry_onpremise_snuba-replacer_1              ... done
Stopping sentry_onpremise_snuba-api_1                   ... done
Stopping sentry_onpremise_redis_1                       ... done
Stopping sentry_onpremise_clickhouse_1                  ... done
Stopping sentry_onpremise_kafka_1                       ... done
Stopping sentry_onpremise_zookeeper_1                   ... done
Removing sentry_onpremise_nginx_1                       ... 
Removing sentry_onpremise_web_1                         ... 
Removing sentry_onpremise_post-process-forwarder_1      ... 
Removing sentry_onpremise_sentry-cleanup_1              ... 
Removing sentry_onpremise_cron_1                        ... 
Removing sentry_onpremise_ingest-consumer_1             ... 
Removing sentry_onpremise_worker_1                      ... 
Removing sentry_onpremise_snuba-cleanup_1               ... 
Removing sentry_onpremise_relay_1                       ... 
Removing sentry_onpremise_router_1                      ... 
Removing sentry_onpremise_symbolicator-cleanup_1        ... 
Removing sentry_onpremise_snuba-consumer_1              ... 
Removing sentry_onpremise_snuba-outcomes-consumer_1     ... 
Removing sentry_onpremise_snuba-sessions-consumer_1     ... 
Removing sentry_onpremise_snuba-transactions-consumer_1 ... 
Removing sentry_onpremise_snuba-replacer_1              ... 
Removing sentry_onpremise_snuba-api_1                   ... 
Removing sentry_onpremise_smtp_1                        ... 
Removing sentry_onpremise_postgres_1                    ... 
Removing sentry_onpremise_symbolicator_1                ... 
Removing sentry_onpremise_memcached_1                   ... 
Removing sentry_onpremise_kafka_1                       ... 
Removing sentry_onpremise_clickhouse_1                  ... 
Removing sentry_onpremise_redis_1                       ... 
Removing sentry_onpremise_zookeeper_1                   ... 
Removing sentry_onpremise_snuba-consumer_1              ... done
Removing sentry_onpremise_snuba-outcomes-consumer_1     ... done
Removing sentry_onpremise_memcached_1                   ... done
Removing sentry_onpremise_snuba-transactions-consumer_1 ... done
Removing sentry_onpremise_symbolicator-cleanup_1        ... done
Removing sentry_onpremise_post-process-forwarder_1      ... done
Removing sentry_onpremise_snuba-sessions-consumer_1     ... done
Removing sentry_onpremise_ingest-consumer_1             ... done
Removing sentry_onpremise_snuba-replacer_1              ... done
Removing sentry_onpremise_smtp_1                        ... done
Removing sentry_onpremise_clickhouse_1                  ... done
Removing sentry_onpremise_snuba-cleanup_1               ... done
Removing sentry_onpremise_sentry-cleanup_1              ... done
Removing sentry_onpremise_snuba-api_1                   ... done
Removing sentry_onpremise_postgres_1                    ... done
Removing sentry_onpremise_worker_1                      ... done
Removing sentry_onpremise_router_1                      ... done
Removing sentry_onpremise_web_1                         ... done
Removing sentry_onpremise_nginx_1                       ... done
Removing sentry_onpremise_kafka_1                       ... done
Removing sentry_onpremise_symbolicator_1                ... done
Removing sentry_onpremise_redis_1                       ... done
Removing sentry_onpremise_relay_1                       ... done
Removing sentry_onpremise_zookeeper_1                   ... done
Removing sentry_onpremise_cron_1                        ... done
Removing network sentry_onpremise_default
Creating network "sentry_onpremise_default" with the default driver
Creating sentry_onpremise_zookeeper_run ... 
Creating sentry_onpremise_zookeeper_run ... done
Creating sentry_onpremise_zookeeper_run ... 
Creating sentry_onpremise_zookeeper_run ... done
Creating sentry_onpremise_zookeeper_run ... 
Creating sentry_onpremise_zookeeper_run ... done
Bootstrapping and migrating Snuba...
Creating sentry_onpremise_redis_1 ... 
Creating sentry_onpremise_zookeeper_1 ... 
Creating sentry_onpremise_clickhouse_1 ... 
Creating sentry_onpremise_zookeeper_1  ... done
Creating sentry_onpremise_kafka_1      ... 
Creating sentry_onpremise_redis_1      ... done
Creating sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_kafka_1      ... done
Creating sentry_onpremise_snuba-api_run ... 
Creating sentry_onpremise_snuba-api_run ... done
2021-05-07 09:35:16,391 Attempting to connect to Kafka (attempt 0)...
2021-05-07 09:35:18,398 Attempting to connect to Kafka (attempt 1)...
2021-05-07 09:35:20,405 Attempting to connect to Kafka (attempt 2)...
2021-05-07 09:35:20,879 Connected to Kafka on attempt 2
2021-05-07 09:35:21,035 Creating Kafka topics...
Creating sentry_onpremise_snuba-api_run ... 
Creating sentry_onpremise_snuba-api_run ... done
Starting migration from 2021-05-03
Migrated 2021-05-03. (1 of 13 partitions done)
Migrated 2021-04-26. (2 of 13 partitions done)
Migrated 2021-04-19. (3 of 13 partitions done)
Migrated 2021-04-12. (4 of 13 partitions done)
Migrated 2021-04-05. (5 of 13 partitions done)
Migrated 2021-03-29. (6 of 13 partitions done)
Migrated 2021-03-22. (7 of 13 partitions done)
Migrated 2021-03-15. (8 of 13 partitions done)
Migrated 2021-03-08. (9 of 13 partitions done)
Migrated 2021-03-01. (10 of 13 partitions done)
Migrated 2021-02-22. (11 of 13 partitions done)
Migrated 2021-02-15. (12 of 13 partitions done)
Migrated 2021-02-08. (13 of 13 partitions done)
Done. Optimizing.
Finished running migrations


Setting up database...
Creating sentry_onpremise_smtp_1 ... 
Creating sentry_onpremise_symbolicator_1 ... 
Creating sentry_onpremise_postgres_1     ... 
Creating sentry_onpremise_memcached_1    ... 
Creating sentry_onpremise_snuba-api_1    ... 
Creating sentry_onpremise_snuba-outcomes-consumer_1 ... 
Creating sentry_onpremise_snuba-replacer_1          ... 
Creating sentry_onpremise_snuba-sessions-consumer_1 ... 
Creating sentry_onpremise_snuba-consumer_1          ... 
Creating sentry_onpremise_snuba-transactions-consumer_1 ... 
Creating sentry_onpremise_smtp_1                        ... done
Creating sentry_onpremise_postgres_1                    ... done
Creating sentry_onpremise_snuba-api_1                   ... done
Creating sentry_onpremise_symbolicator_1                ... done
Creating sentry_onpremise_memcached_1                   ... done
Creating sentry_onpremise_snuba-transactions-consumer_1 ... done
Creating sentry_onpremise_snuba-sessions-consumer_1     ... done
Creating sentry_onpremise_snuba-outcomes-consumer_1     ... done
Creating sentry_onpremise_snuba-replacer_1              ... done
Creating sentry_onpremise_snuba-consumer_1              ... done
Creating sentry_onpremise_web_run                       ... 
Creating sentry_onpremise_web_run                       ... done
09:35:47 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
09:35:51 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'slack.legacy-app'
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying nodestore.0002_nodestore_no_dictfield... OK
  Applying sentry.0149_bigint... OK
  Applying sentry.0150_remove_userreport_eventattachment_constraints... OK
  Applying sentry.0151_add_world_map_dashboard_widget_type... OK
Integrations: 100% |#############################################| Time: 0:00:00
 OK
  Applying sentry.0153_add_big_number_dashboard_widget_type... OK
  Applying sentry.0154_groupedmessage_inbox_sort... OK
  Applying sentry.0155_add_dashboard_query_orderby... OK
  Applying sentry.0156_add_mark_reviewed_activity... OK
  Applying sentry.0157_make_repositoryprojectpathconfig_organization_integration_nullable... OK
  Applying sentry.0158_create_externalteam_table... OK
  Applying sentry.0159_create_externaluser_table... OK
  Applying sentry.0160_create_projectcodeowners_table... OK
  Applying sentry.0161_add_saved_search_sort... OK
Saved Searchs: 100% |############################################| Time: 0:00:00
 OK
  Applying sentry.0163_add_organizationmember_and_external_name... OK
  Applying sentry.0164_add_protect_on_delete_codeowners... OK
  Applying sentry.0165_metric_alerts_fix_group_ids... OK
  Applying sentry.0166_create_notificationsetting_table... OK
  Applying sentry.0167_rm_organization_integration_from_projectcodeowners... OK
  Applying sentry.0168_demo_orgs_users... OK
  Applying sentry.0169_delete_organization_integration_from_projectcodeowners... OK
  Applying sentry.0170_actor_introduction... OK
Users: 100% |####################################################| Time: 0:00:00
Teams: 100% |####################################################| Time: 0:00:00
 OK
  Applying sentry.0172_rule_owner_fields... OK
  Applying sentry.0173_remove_demo_flag... OK
  Applying sentry.0174_my_issues_saved_search... OK
  Applying sentry.0175_make_targets_nullable... OK
  Applying sentry.0176_remove_targets... OK
  Applying sentry.0177_drop_targets... OK
  Applying sentry.0178_add_new_target_column... OK
Discover Saved Querys: 100% |####################################| Time: 0:00:00
 OK
  Applying sentry.0180_add_saved_search_sorts... OK
User Options: 100% |#############################################| Time: 0:00:00
 OK
Discover Saved Querys: 100% |####################################| Time: 0:00:00
 OK
  Applying sentry.0183_make_codemapping_unique_on_projectcodeowners... OK
User Options: 100% |#############################################| Time: 0:00:00
 OK
User Options: 100% |#############################################| Time: 0:00:00
 OK
  Applying sentry.0186_add_externalactor... OK
Creating missing DSNs
Correcting Group.num_comments counter

----------------
You're all done! Run the following command to get Sentry running:

  docker-compose up -d
```

**Comment by soullivaneuh** [comment]
I also received be e-mail not found internal error on the events namespace:

```
NotFoundError: GET /issues/230/events/latest/ 404
  at value (/_static/dist/sentry/app.214db130971bf631e23f.js:1:59388)
  at c (/_static/dist/sentry/vendor.7643a38b726be847e076.js:2:2028355)
  at u/i._invoke</< (/_static/dist/sentry/vendor.7643a38b726be847e076.js:2:2028144)
  at x/</< (/_static/dist/sentry/vendor.7643a38b726be847e076.js:2:2028780)
  at r (/_static/dist/sentry/vendor.7643a38b726be847e076.js:2:59729)
...
(45 additional frame(s) were not displayed)
```

Of course, if I try to access the internal issue, I have the same symptom.

**Comment by soullivaneuh** [comment]
Forget it, it was a chair/keyboard interface issue.

A simple `git pull` on the `onpremise` setup following by a `install.sh` run seems to fix the issue.
