### ISSUE TITLE
Sentry upgrade failed. 21.3.0 -> 21.4.1

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#956]
### Version Information

Version: 21.3.0

### Steps to Reproduce

1. Run sentry upgrade
1. Notice error

`ImportError: cannot import name 'AlertRuleSerializer'`

### Expected Result

Sentry upgrades

### Actual Result

```sh
Creating sentry_web_run ... done
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 131, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/settings.py", line 161, in configure
    skip_service_validation=skip_service_validation,
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/initializer.py", line 353, in initialize_app
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python3.6/site-packages/sentry_extensions/apps.py", line 8, in ready
    from sentry.api import urls
  File "/usr/local/lib/python3.6/site-packages/sentry/api/urls.py", line 12, in <module>
    from sentry.incidents.endpoints.organization_alert_rule_available_action_index import (
  File "/usr/local/lib/python3.6/site-packages/sentry/incidents/endpoints/organization_alert_rule_available_action_index.py", line 10, in <module>
    from sentry.incidents.endpoints.serializers import action_target_type_to_string
  File "/usr/local/lib/python3.6/site-packages/sentry/incidents/endpoints/serializers.py", line 39, in <module>
    from sentry.integrations.slack.utils import validate_channel_id
  File "/usr/local/lib/python3.6/site-packages/sentry/integrations/slack/__init__.py", line 6, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/imports.py", line 42, in import_submodules
    module = __import__(module_name, globals(), locals(), ["__name__"])
  File "/usr/local/lib/python3.6/site-packages/sentry/integrations/slack/tasks.py", line 8, in <module>
    from sentry.incidents.endpoints.serializers import AlertRuleSerializer
ImportError: cannot import name 'AlertRuleSerializer'
```

Any ideas?

**Comment by max-wittig** [comment]
Same error, when trying to go directly to 21.5.1
