### ISSUE TITLE
run sentry with traefik proxy 

### ISSUE THREAD

**Issue by daton89** [getsentry/onpremise#99]
I'm trying to running sentry behind traefik proxy. 

```

version: '2'
services:
  base:
    hostname: base
    restart: unless-stopped
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    networks:
      - sentry_platform

  smtp:
    hostname: smtp
    restart: unless-stopped
    image: tianon/exim4
    networks:
      - sentry_platform

  memcached:
    hostname: memcached
    restart: unless-stopped
    image: memcached:1.4
    networks:
      - sentry_platform    

  redis:
    hostname: redis
    restart: unless-stopped
    image: redis:3.2-alpine
    networks:
      - sentry_platform    

  postgres:
    hostname: postgres
    restart: unless-stopped
    image: postgres:9.5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - sentry_platform

  web:
    hostname: web
    restart: unless-stopped
    extends: base
    links:
      - redis
      - postgres
      - memcached
      - smtp
    labels:
      - traefik.backend=web
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.rule=Host:sentry.myhost.com
      - traefik.port=9000
    networks:
      - traefik_proxy
      - sentry_platform
  
  cron:
    hostname: cron
    restart: unless-stopped
    extends: base
    command: run cron
    links:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - sentry_platform

  worker:
    hostname: worker
    restart: unless-stopped
    extends: base
    command: run worker
    links:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - sentry_platform

networks:
  traefik_proxy:
    external: true
  sentry_platform:
    external: false
    driver: bridge
```

the first problem is when i run the migrate 

```
root@fedora-atomic:/home/fedora/sentry# docker-compose run --rm web upgrade
Starting sentry_smtp_1 ...
Starting sentry_postgres_1 ...
Starting sentry_postgres_1 ... done
Starting sentry_memcached_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/options/store.py", line 165, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: ProgrammingError('relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n                                                             ^\n',)
SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = %s
14:05:26 [ERROR] sentry: option.failed-lookup (key=u'github.apps-install-url')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 75, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 245, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: ProgrammingError('relation "sentry_project" does not exist\nLINE 1: ...roject"."flags", "sentry_project"."platform" FROM "sentry_pr...\n                                                             ^\n',)
SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event", "sentry_project"."flags", "sentry_project"."platform" FROM "sentry_project" WHERE "sentry_project"."id" = %s
14:05:26 [ERROR] sentry.errors: Unable to fetch internal project
14:05:26 [INFO] sentry.plugins.github: apps-not-configured

Syncing...
Creating tables ...
Creating table django_admin_log
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table south_migrationhistory
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
... more
```

then when i run docker-compose up -d it seems that the containers doesn't deal to each other... 

traefik generate the ssl certificate so the result should be access sentry from https://sentry.myhost.com
but in the web container logs i have: sentry Unable to fetch ProjectKey for internal project

i tried to use networks instead of links because when i use traefik i need to link the web on the traefik proxy network to make able traefik to proxy the request to web 

so i made a sentry_platform network to make containers talk to each other, and then i tried to use links and networks in the same time... 

i'm running docker on a digitalocean droplet with 3gb ram 1cpu and 60gb hd

**Comment by dcramer** [comment]
I'd consider this generally a support request (if there's something actionable that is broken in Sentry let us know), so please use the appropriate channels.

https://sentry.io/support/

**Comment by revolunet** [comment]
the `ProjectKey` error usually means the initial migration failed. try to clear the data folder and try `web upgrade` to restart them

**Comment by revolunet** [comment]
Also, here's a traefik compatible docker-compose :

```yml
version: '3.4'
x-defaults: &defaults
  restart: unless-stopped
  build: .
  environment:
    # Run `docker-compose run web config generate-secret-key`
    # to get the SENTRY_SECRET_KEY value.
    SENTRY_SECRET_KEY: ''
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files

services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4
    networks:
      - sentry
    labels:
      - "traefik.enable=false"

  memcached:
    restart: unless-stopped
    image: memcached:1.4
    labels:
      - "traefik.enable=false"
    networks:
      - sentry

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    labels:
      - "traefik.enable=false"
    networks:
      - sentry

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - sentry

  web:
    <<: *defaults
    labels:
      - "traefik.backend=sentry"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:sentry.pouet.com"
      - "traefik.docker.network=traefik_webgateway"
    networks:
      - web
      - sentry

  cron:
    <<: *defaults
    command: run cron
    labels:
      - "traefik.enable=false"
    networks:
      - sentry

  worker:
    <<: *defaults
    command: run worker
    networks:
      - sentry
    labels:
      - "traefik.enable=false"

networks:
  sentry:
    driver: bridge
  web:
    external:
      name: traefik_webgateway

volumes:
    sentry-data:
    sentry-postgres:
```
